/**
 * Singapore / Hong Kong Food Database
 * Comprehensive nutritional data for local Southeast Asian cuisine.
 * All values are per serving, calories in kcal, macros in grams.
 */

export type FoodCategory =
  | 'hawker'
  | 'home-cooked'
  | 'restaurant'
  | 'breakfast'
  | 'snack'
  | 'beverage'
  | 'protein'
  | 'vegetable'
  | 'carb';

export type CuisineType =
  | 'singapore'
  | 'malaysian'
  | 'chinese'
  | 'japanese'
  | 'western'
  | 'indian'
  | 'thai'
  | 'korean'
  | 'fusion';

export interface FoodItem {
  id: string;
  name: string;
  category: FoodCategory;
  cuisine: CuisineType;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  fiber: number;
  isQuickPrep: boolean;
  isHealthyOption: boolean;
  tags: string[];
  servingSize: string;
  localName?: string;
}

/* ================================================================
   Singapore / HK Food Database — 120 items
   ================================================================ */

export const SINGAPORE_FOOD_DATABASE: FoodItem[] = [
  // ── Hawker Favourites ──────────────────────────────────────────
  {
    id: 'sf-001',
    name: 'Hainanese Chicken Rice',
    localName: '海南鸡饭',
    category: 'hawker',
    cuisine: 'singapore',
    calories: 620,
    protein: 28,
    carbs: 72,
    fats: 22,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-carb', 'halal', 'classic'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-002',
    name: 'Char Kway Teow',
    localName: '炒粿条',
    category: 'hawker',
    cuisine: 'singapore',
    calories: 742,
    protein: 18,
    carbs: 78,
    fats: 40,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-fat', 'high-calorie', 'spicy', 'classic'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-003',
    name: 'Laksa',
    localName: '叻沙',
    category: 'hawker',
    cuisine: 'singapore',
    calories: 580,
    protein: 20,
    carbs: 62,
    fats: 28,
    fiber: 4,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['spicy', 'coconut', 'classic'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-004',
    name: 'Hokkien Mee',
    localName: '福建面',
    category: 'hawker',
    cuisine: 'singapore',
    calories: 560,
    protein: 22,
    carbs: 68,
    fats: 22,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['seafood', 'classic'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-005',
    name: 'Mee Goreng',
    localName: '印度炒面',
    category: 'hawker',
    cuisine: 'indian',
    calories: 510,
    protein: 16,
    carbs: 70,
    fats: 18,
    fiber: 4,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['spicy', 'halal', 'classic'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-006',
    name: 'Nasi Lemak',
    localName: '椰浆饭',
    category: 'hawker',
    cuisine: 'malaysian',
    calories: 680,
    protein: 18,
    carbs: 78,
    fats: 32,
    fiber: 5,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['coconut', 'spicy', 'halal', 'classic'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-007',
    name: 'Roti Prata (Plain)',
    localName: '印度煎饼',
    category: 'hawker',
    cuisine: 'indian',
    calories: 320,
    protein: 8,
    carbs: 48,
    fats: 12,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['vegetarian', 'halal', 'classic'],
    servingSize: '2 pieces',
  },
  {
    id: 'sf-008',
    name: 'Egg Prata',
    localName: '鸡蛋印度煎饼',
    category: 'hawker',
    cuisine: 'indian',
    calories: 440,
    protein: 16,
    carbs: 48,
    fats: 20,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['halal', 'classic', 'high-protein'],
    servingSize: '2 pieces',
  },
  {
    id: 'sf-009',
    name: 'Wanton Mee',
    localName: '云吞面',
    category: 'hawker',
    cuisine: 'chinese',
    calories: 480,
    protein: 24,
    carbs: 62,
    fats: 14,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['classic', 'pork'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-010',
    name: 'Fishball Noodle Soup',
    localName: '鱼丸面',
    category: 'hawker',
    cuisine: 'singapore',
    calories: 370,
    protein: 22,
    carbs: 52,
    fats: 8,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['low-fat', 'classic', 'halal'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-011',
    name: 'Duck Rice',
    localName: '鸭饭',
    category: 'hawker',
    cuisine: 'chinese',
    calories: 650,
    protein: 32,
    carbs: 68,
    fats: 26,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-protein', 'classic'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-012',
    name: 'Satay (10 sticks)',
    localName: '沙爹',
    category: 'hawker',
    cuisine: 'singapore',
    calories: 450,
    protein: 30,
    carbs: 18,
    fats: 28,
    fiber: 1,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-protein', 'halal', 'classic', 'peanut'],
    servingSize: '10 sticks with sauce',
  },
  {
    id: 'sf-013',
    name: 'Bak Kut Teh',
    localName: '肉骨茶',
    category: 'hawker',
    cuisine: 'chinese',
    calories: 420,
    protein: 32,
    carbs: 12,
    fats: 26,
    fiber: 1,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-protein', 'soup', 'pork'],
    servingSize: '1 bowl with rice',
  },
  {
    id: 'sf-014',
    name: 'Chili Crab',
    localName: '辣椒螃蟹',
    category: 'restaurant',
    cuisine: 'singapore',
    calories: 780,
    protein: 62,
    carbs: 48,
    fats: 38,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-protein', 'seafood', 'spicy', 'classic'],
    servingSize: '1 serving',
  },
  {
    id: 'sf-015',
    name: 'Cereal Prawn',
    localName: '麦片虾',
    category: 'restaurant',
    cuisine: 'singapore',
    calories: 520,
    protein: 38,
    carbs: 32,
    fats: 26,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-protein', 'seafood', 'classic'],
    servingSize: '1 serving',
  },
  {
    id: 'sf-016',
    name: 'Oyster Omelette',
    localName: '蚵仔煎',
    category: 'hawker',
    cuisine: 'singapore',
    calories: 460,
    protein: 18,
    carbs: 28,
    fats: 30,
    fiber: 1,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['seafood', 'high-fat', 'classic'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-017',
    name: 'Fried Carrot Cake (White)',
    localName: '菜头粿（白）',
    category: 'hawker',
    cuisine: 'singapore',
    calories: 480,
    protein: 10,
    carbs: 62,
    fats: 22,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['vegetarian', 'classic'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-018',
    name: 'Fried Carrot Cake (Black)',
    localName: '菜头粿（黑）',
    category: 'hawker',
    cuisine: 'singapore',
    calories: 520,
    protein: 10,
    carbs: 66,
    fats: 24,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['vegetarian', 'sweet', 'classic'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-019',
    name: 'Mee Rebus',
    localName: '马来卤面',
    category: 'hawker',
    cuisine: 'malaysian',
    calories: 520,
    protein: 16,
    carbs: 72,
    fats: 18,
    fiber: 5,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['halal', 'spicy', 'classic'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-020',
    name: 'Mee Siam',
    localName: '米暹',
    category: 'hawker',
    cuisine: 'singapore',
    calories: 450,
    protein: 14,
    carbs: 68,
    fats: 14,
    fiber: 4,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['halal', 'spicy', 'sour', 'classic'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-021',
    name: 'Nasi Padang (mixed)',
    localName: '巴东饭',
    category: 'hawker',
    cuisine: 'indian',
    calories: 720,
    protein: 28,
    carbs: 82,
    fats: 30,
    fiber: 6,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['halal', 'spicy', 'variety'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-022',
    name: 'Roti John',
    localName: '约翰面包',
    category: 'hawker',
    cuisine: 'fusion',
    calories: 520,
    protein: 22,
    carbs: 52,
    fats: 24,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['halal', 'spicy', 'egg'],
    servingSize: '1 serving',
  },
  {
    id: 'sf-023',
    name: 'Lontong',
    localName: '隆冬',
    category: 'hawker',
    cuisine: 'malaysian',
    calories: 480,
    protein: 14,
    carbs: 68,
    fats: 16,
    fiber: 5,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['halal', 'coconut', 'classic'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-024',
    name: 'Popiah',
    localName: '薄饼',
    category: 'hawker',
    cuisine: 'singapore',
    calories: 280,
    protein: 8,
    carbs: 38,
    fats: 10,
    fiber: 4,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['low-calorie', 'vegetarian', 'fresh'],
    servingSize: '2 rolls',
  },

  // ── Home-Cooked Dishes ─────────────────────────────────────────
  {
    id: 'sf-025',
    name: 'Steamed Fish with Soy Sauce',
    localName: '清蒸鱼',
    category: 'home-cooked',
    cuisine: 'chinese',
    calories: 280,
    protein: 38,
    carbs: 8,
    fats: 10,
    fiber: 1,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['high-protein', 'low-carb', 'low-fat', 'omega-3'],
    servingSize: '1 fillet',
  },
  {
    id: 'sf-026',
    name: 'Stir-fried Kai Lan with Garlic',
    localName: '蒜炒芥兰',
    category: 'home-cooked',
    cuisine: 'chinese',
    calories: 120,
    protein: 4,
    carbs: 12,
    fats: 6,
    fiber: 4,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-calorie', 'vegetarian', 'vitamin-rich'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-027',
    name: 'Braised Pork Belly',
    localName: '红烧肉',
    category: 'home-cooked',
    cuisine: 'chinese',
    calories: 520,
    protein: 22,
    carbs: 22,
    fats: 36,
    fiber: 1,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-fat', 'pork', 'classic'],
    servingSize: '1 bowl with rice',
  },
  {
    id: 'sf-028',
    name: 'Steamed Egg',
    localName: '蒸蛋',
    category: 'home-cooked',
    cuisine: 'chinese',
    calories: 180,
    protein: 14,
    carbs: 6,
    fats: 11,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'low-carb', 'quick'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-029',
    name: 'Lotus Root Soup',
    localName: '莲藕汤',
    category: 'home-cooked',
    cuisine: 'chinese',
    calories: 220,
    protein: 18,
    carbs: 22,
    fats: 8,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['soup', 'low-fat', 'comfort'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-030',
    name: 'ABC Soup',
    localName: 'ABC汤',
    category: 'home-cooked',
    cuisine: 'chinese',
    calories: 160,
    protein: 14,
    carbs: 18,
    fats: 4,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['soup', 'low-calorie', 'comfort'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-031',
    name: 'Watercress Soup',
    localName: '西洋菜汤',
    category: 'home-cooked',
    cuisine: 'chinese',
    calories: 140,
    protein: 16,
    carbs: 10,
    fats: 4,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['soup', 'low-calorie', 'vitamin-rich'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-032',
    name: 'Claypot Rice',
    localName: '煲仔饭',
    category: 'home-cooked',
    cuisine: 'chinese',
    calories: 620,
    protein: 24,
    carbs: 78,
    fats: 22,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-carb', 'comfort', 'classic'],
    servingSize: '1 pot',
  },
  {
    id: 'sf-033',
    name: 'Steamed Chicken with Mushrooms',
    localName: '冬菇蒸鸡',
    category: 'home-cooked',
    cuisine: 'chinese',
    calories: 320,
    protein: 38,
    carbs: 10,
    fats: 14,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['high-protein', 'low-carb', 'gluten-free'],
    servingSize: '1 serving',
  },
  {
    id: 'sf-034',
    name: 'Sweet & Sour Pork',
    localName: '咕噜肉',
    category: 'home-cooked',
    cuisine: 'chinese',
    calories: 480,
    protein: 22,
    carbs: 48,
    fats: 22,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['sweet', 'pork', 'classic'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-035',
    name: 'Mapo Tofu',
    localName: '麻婆豆腐',
    category: 'home-cooked',
    cuisine: 'chinese',
    calories: 280,
    protein: 18,
    carbs: 14,
    fats: 18,
    fiber: 3,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['spicy', 'high-protein', 'vegetarian'],
    servingSize: '1 bowl with rice',
  },
  {
    id: 'sf-036',
    name: 'Stir-fried Morning Glory',
    localName: '炒通菜',
    category: 'home-cooked',
    cuisine: 'chinese',
    calories: 100,
    protein: 4,
    carbs: 10,
    fats: 5,
    fiber: 4,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-calorie', 'vegetarian', 'quick'],
    servingSize: '1 plate',
  },

  // ── Protein Sources ────────────────────────────────────────────
  {
    id: 'sf-037',
    name: 'Grilled Chicken Breast',
    category: 'protein',
    cuisine: 'western',
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'low-carb', 'low-fat', 'gluten-free'],
    servingSize: '100g',
  },
  {
    id: 'sf-038',
    name: 'Salmon Fillet (Grilled)',
    category: 'protein',
    cuisine: 'western',
    calories: 280,
    protein: 26,
    carbs: 0,
    fats: 20,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'omega-3', 'keto', 'gluten-free'],
    servingSize: '150g',
  },
  {
    id: 'sf-039',
    name: 'Beef Steak (Sirloin)',
    category: 'protein',
    cuisine: 'western',
    calories: 310,
    protein: 32,
    carbs: 0,
    fats: 20,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'iron-rich', 'keto', 'gluten-free'],
    servingSize: '150g',
  },
  {
    id: 'sf-040',
    name: 'Firm Tofu (Steamed)',
    category: 'protein',
    cuisine: 'chinese',
    calories: 144,
    protein: 17,
    carbs: 6,
    fats: 7,
    fiber: 1,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['vegetarian', 'high-protein', 'low-carb', 'vegan'],
    servingSize: '150g',
  },
  {
    id: 'sf-041',
    name: 'Whole Eggs (2)',
    category: 'protein',
    cuisine: 'western',
    calories: 140,
    protein: 12,
    carbs: 1,
    fats: 10,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'keto', 'vitamin-rich'],
    servingSize: '2 eggs',
  },
  {
    id: 'sf-042',
    name: 'Greek Yogurt (Plain)',
    category: 'protein',
    cuisine: 'western',
    calories: 130,
    protein: 22,
    carbs: 8,
    fats: 0,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'probiotic', 'low-fat'],
    servingSize: '200g',
  },
  {
    id: 'sf-043',
    name: 'Whey Protein Shake',
    category: 'protein',
    cuisine: 'western',
    calories: 120,
    protein: 24,
    carbs: 3,
    fats: 2,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'low-carb', 'post-workout'],
    servingSize: '1 scoop',
  },
  {
    id: 'sf-044',
    name: 'Canned Tuna in Water',
    category: 'protein',
    cuisine: 'western',
    calories: 116,
    protein: 26,
    carbs: 0,
    fats: 1,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'low-fat', 'omega-3'],
    servingSize: '1 can (150g)',
  },
  {
    id: 'sf-045',
    name: 'Prawns (Steamed)',
    category: 'protein',
    cuisine: 'singapore',
    calories: 100,
    protein: 24,
    carbs: 0,
    fats: 0.2,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'low-fat', 'omega-3', 'gluten-free'],
    servingSize: '150g',
  },
  {
    id: 'sf-046',
    name: 'Chicken Thigh (Skinless)',
    category: 'protein',
    cuisine: 'western',
    calories: 190,
    protein: 28,
    carbs: 0,
    fats: 8,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'low-carb', 'gluten-free'],
    servingSize: '150g',
  },

  // ── Healthy / Modern Options ───────────────────────────────────
  {
    id: 'sf-047',
    name: 'Acai Bowl',
    category: 'breakfast',
    cuisine: 'fusion',
    calories: 380,
    protein: 10,
    carbs: 58,
    fats: 14,
    fiber: 10,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['antioxidant', 'fiber-rich', 'vegan', 'superfood'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-048',
    name: 'Asian Grain Bowl',
    category: 'home-cooked',
    cuisine: 'fusion',
    calories: 480,
    protein: 28,
    carbs: 58,
    fats: 16,
    fiber: 10,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'fiber-rich', 'balanced'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-049',
    name: 'Salad with Asian Sesame Dressing',
    category: 'vegetable',
    cuisine: 'fusion',
    calories: 220,
    protein: 10,
    carbs: 18,
    fats: 14,
    fiber: 6,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-calorie', 'vegetarian', 'vitamin-rich'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-050',
    name: 'Zucchini Noodles with Chicken',
    category: 'home-cooked',
    cuisine: 'fusion',
    calories: 280,
    protein: 32,
    carbs: 12,
    fats: 12,
    fiber: 4,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-carb', 'high-protein', 'keto', 'gluten-free'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-051',
    name: 'Cauliflower Rice Stir-fry',
    category: 'vegetable',
    cuisine: 'fusion',
    calories: 180,
    protein: 10,
    carbs: 16,
    fats: 10,
    fiber: 6,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-carb', 'keto', 'vegan', 'gluten-free'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-052',
    name: 'Chicken Rice Bowl (No Skin)',
    category: 'home-cooked',
    cuisine: 'singapore',
    calories: 450,
    protein: 34,
    carbs: 52,
    fats: 10,
    fiber: 3,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'balanced', 'low-fat'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-053',
    name: 'Quinoa Bowl with Tofu',
    category: 'home-cooked',
    cuisine: 'fusion',
    calories: 420,
    protein: 20,
    carbs: 52,
    fats: 14,
    fiber: 8,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['vegetarian', 'high-fiber', 'vegan'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-054',
    name: 'Edamame',
    category: 'snack',
    cuisine: 'japanese',
    calories: 180,
    protein: 16,
    carbs: 14,
    fats: 8,
    fiber: 8,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'vegan', 'snack', 'gluten-free'],
    servingSize: '1 cup',
  },
  {
    id: 'sf-055',
    name: 'Chia Pudding',
    category: 'breakfast',
    cuisine: 'western',
    calories: 240,
    protein: 10,
    carbs: 24,
    fats: 14,
    fiber: 14,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['omega-3', 'fiber-rich', 'vegan'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-056',
    name: 'Grilled Fish with Vegetables',
    category: 'home-cooked',
    cuisine: 'western',
    calories: 320,
    protein: 36,
    carbs: 16,
    fats: 12,
    fiber: 6,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'low-carb', 'gluten-free'],
    servingSize: '1 plate',
  },

  // ── Western ────────────────────────────────────────────────────
  {
    id: 'sf-057',
    name: 'Pasta Bolognese',
    category: 'restaurant',
    cuisine: 'western',
    calories: 620,
    protein: 32,
    carbs: 78,
    fats: 20,
    fiber: 6,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-carb', 'high-protein', 'comfort'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-058',
    name: 'Fish & Chips',
    category: 'restaurant',
    cuisine: 'western',
    calories: 780,
    protein: 32,
    carbs: 82,
    fats: 36,
    fiber: 5,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-calorie', 'fried', 'comfort'],
    servingSize: '1 serving',
  },
  {
    id: 'sf-059',
    name: 'Cheeseburger',
    category: 'restaurant',
    cuisine: 'western',
    calories: 650,
    protein: 32,
    carbs: 52,
    fats: 34,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-calorie', 'high-fat', 'beef'],
    servingSize: '1 burger',
  },
  {
    id: 'sf-060',
    name: 'Margherita Pizza',
    category: 'restaurant',
    cuisine: 'western',
    calories: 720,
    protein: 28,
    carbs: 88,
    fats: 28,
    fiber: 5,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-carb', 'vegetarian', 'comfort'],
    servingSize: '3 slices',
  },
  {
    id: 'sf-061',
    name: 'Club Sandwich',
    category: 'restaurant',
    cuisine: 'western',
    calories: 520,
    protein: 28,
    carbs: 48,
    fats: 24,
    fiber: 5,
    isQuickPrep: true,
    isHealthyOption: false,
    tags: ['high-protein', 'chicken', 'quick'],
    servingSize: '1 sandwich',
  },
  {
    id: 'sf-062',
    name: 'Caesar Salad with Chicken',
    category: 'restaurant',
    cuisine: 'western',
    calories: 420,
    protein: 36,
    carbs: 18,
    fats: 24,
    fiber: 5,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'low-carb', 'gluten-free-option'],
    servingSize: '1 bowl',
  },

  // ── Japanese ───────────────────────────────────────────────────
  {
    id: 'sf-063',
    name: 'Salmon Sushi Set (8pc)',
    localName: 'サーモン寿司',
    category: 'restaurant',
    cuisine: 'japanese',
    calories: 380,
    protein: 20,
    carbs: 52,
    fats: 10,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['omega-3', 'balanced', 'fresh'],
    servingSize: '8 pieces',
  },
  {
    id: 'sf-064',
    name: 'Tonkotsu Ramen',
    localName: '豚骨ラーメン',
    category: 'restaurant',
    cuisine: 'japanese',
    calories: 580,
    protein: 28,
    carbs: 68,
    fats: 22,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-carb', 'pork', 'comfort'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-065',
    name: 'Chicken Bento',
    localName: '鶏肉弁当',
    category: 'restaurant',
    cuisine: 'japanese',
    calories: 620,
    protein: 32,
    carbs: 78,
    fats: 20,
    fiber: 6,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['balanced', 'variety'],
    servingSize: '1 box',
  },
  {
    id: 'sf-066',
    name: 'Teriyaki Chicken Don',
    localName: '照り焼きチキン丼',
    category: 'restaurant',
    cuisine: 'japanese',
    calories: 640,
    protein: 36,
    carbs: 82,
    fats: 18,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-protein', 'high-carb', 'sweet'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-067',
    name: 'Salmon Sashimi (10pc)',
    localName: 'サーモン刺身',
    category: 'restaurant',
    cuisine: 'japanese',
    calories: 320,
    protein: 30,
    carbs: 2,
    fats: 22,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'low-carb', 'keto', 'omega-3'],
    servingSize: '10 slices',
  },
  {
    id: 'sf-068',
    name: 'Miso Soup with Tofu',
    localName: '味噌汁',
    category: 'home-cooked',
    cuisine: 'japanese',
    calories: 80,
    protein: 6,
    carbs: 8,
    fats: 3,
    fiber: 2,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-calorie', 'probiotic', 'vegan'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-069',
    name: 'Unagi Don',
    localName: '鰻丼',
    category: 'restaurant',
    cuisine: 'japanese',
    calories: 680,
    protein: 30,
    carbs: 88,
    fats: 22,
    fiber: 1,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-carb', 'sweet', 'omega-3'],
    servingSize: '1 bowl',
  },

  // ── Korean ─────────────────────────────────────────────────────
  {
    id: 'sf-070',
    name: 'Bibimbap',
    localName: '비빔밥',
    category: 'restaurant',
    cuisine: 'korean',
    calories: 580,
    protein: 22,
    carbs: 82,
    fats: 18,
    fiber: 10,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['balanced', 'vegetarian-option', 'spicy'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-071',
    name: 'Korean BBQ Beef (Bulgogi)',
    localName: '불고기',
    category: 'restaurant',
    cuisine: 'korean',
    calories: 480,
    protein: 38,
    carbs: 28,
    fats: 24,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-protein', 'sweet', 'beef'],
    servingSize: '1 serving',
  },
  {
    id: 'sf-072',
    name: 'Kimchi Stew (Kimchi-jjigae)',
    localName: '김치찌개',
    category: 'home-cooked',
    cuisine: 'korean',
    calories: 320,
    protein: 20,
    carbs: 18,
    fats: 18,
    fiber: 4,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['spicy', 'probiotic', 'comfort'],
    servingSize: '1 bowl with rice',
  },
  {
    id: 'sf-073',
    name: 'Japchae',
    localName: '잡채',
    category: 'home-cooked',
    cuisine: 'korean',
    calories: 420,
    protein: 14,
    carbs: 62,
    fats: 14,
    fiber: 4,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['sweet', 'vegetarian', 'glass-noodles'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-074',
    name: 'Korean Fried Chicken',
    localName: '치킨',
    category: 'restaurant',
    cuisine: 'korean',
    calories: 720,
    protein: 42,
    carbs: 52,
    fats: 38,
    fiber: 1,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-calorie', 'fried', 'sweet-spicy'],
    servingSize: '6 pieces',
  },
  {
    id: 'sf-075',
    name: 'Sundubu-jjigae',
    localName: '순두부찌개',
    category: 'home-cooked',
    cuisine: 'korean',
    calories: 280,
    protein: 22,
    carbs: 12,
    fats: 16,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['spicy', 'high-protein', 'comfort'],
    servingSize: '1 bowl',
  },

  // ── Breakfast ──────────────────────────────────────────────────
  {
    id: 'sf-076',
    name: 'Overnight Oats',
    category: 'breakfast',
    cuisine: 'western',
    calories: 340,
    protein: 14,
    carbs: 52,
    fats: 10,
    fiber: 8,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-fiber', 'balanced', 'prep-ahead'],
    servingSize: '1 jar',
  },
  {
    id: 'sf-077',
    name: 'Smoothie Bowl',
    category: 'breakfast',
    cuisine: 'western',
    calories: 380,
    protein: 12,
    carbs: 58,
    fats: 14,
    fiber: 10,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['vitamin-rich', 'vegan', 'superfood'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-078',
    name: 'Avocado Toast',
    category: 'breakfast',
    cuisine: 'western',
    calories: 420,
    protein: 14,
    carbs: 42,
    fats: 24,
    fiber: 10,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['healthy-fats', 'fiber-rich', 'vegetarian'],
    servingSize: '2 slices',
  },
  {
    id: 'sf-079',
    name: 'Eggs Benedict',
    category: 'breakfast',
    cuisine: 'western',
    calories: 560,
    protein: 26,
    carbs: 38,
    fats: 34,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-protein', 'high-fat', 'brunch'],
    servingSize: '2 halves',
  },
  {
    id: 'sf-080',
    name: 'Chicken Congee',
    localName: '鸡粥',
    category: 'breakfast',
    cuisine: 'chinese',
    calories: 280,
    protein: 22,
    carbs: 36,
    fats: 6,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['comfort', 'easy-digest', 'low-fat'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-081',
    name: 'Century Egg Porridge',
    localName: '皮蛋瘦肉粥',
    category: 'breakfast',
    cuisine: 'chinese',
    calories: 320,
    protein: 20,
    carbs: 38,
    fats: 10,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['comfort', 'classic', 'pork'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-082',
    name: 'Kaya Toast with Eggs',
    localName: '咖椰吐司',
    category: 'breakfast',
    cuisine: 'singapore',
    calories: 420,
    protein: 14,
    carbs: 52,
    fats: 18,
    fiber: 3,
    isQuickPrep: true,
    isHealthyOption: false,
    tags: ['sweet', 'classic', 'coconut'],
    servingSize: '2 slices with eggs',
  },
  {
    id: 'sf-083',
    name: 'Soft Boiled Eggs (2)',
    localName: '半生熟蛋',
    category: 'breakfast',
    cuisine: 'singapore',
    calories: 140,
    protein: 12,
    carbs: 1,
    fats: 10,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'keto', 'classic', 'quick'],
    servingSize: '2 eggs',
  },
  {
    id: 'sf-084',
    name: 'Peanut Butter Toast',
    category: 'breakfast',
    cuisine: 'western',
    calories: 380,
    protein: 14,
    carbs: 38,
    fats: 20,
    fiber: 4,
    isQuickPrep: true,
    isHealthyOption: false,
    tags: ['quick', 'vegetarian', 'protein'],
    servingSize: '2 slices',
  },

  // ── Beverages ──────────────────────────────────────────────────
  {
    id: 'sf-085',
    name: 'Fresh Coconut Water',
    localName: '椰子水',
    category: 'beverage',
    cuisine: 'singapore',
    calories: 45,
    protein: 2,
    carbs: 9,
    fats: 0,
    fiber: 3,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-calorie', 'hydration', 'electrolytes', 'natural'],
    servingSize: '1 cup (240ml)',
  },
  {
    id: 'sf-086',
    name: 'Barley Drink',
    localName: '薏米水',
    category: 'beverage',
    cuisine: 'chinese',
    calories: 120,
    protein: 2,
    carbs: 28,
    fats: 0,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['cooling', 'low-fat', 'traditional'],
    servingSize: '1 cup (300ml)',
  },
  {
    id: 'sf-087',
    name: 'Grass Jelly Drink',
    localName: '仙草水',
    category: 'beverage',
    cuisine: 'chinese',
    calories: 80,
    protein: 1,
    carbs: 18,
    fats: 0,
    fiber: 2,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-calorie', 'cooling', 'traditional'],
    servingSize: '1 cup (300ml)',
  },
  {
    id: 'sf-088',
    name: 'Soy Milk (Unsweetened)',
    localName: '豆奶',
    category: 'beverage',
    cuisine: 'chinese',
    calories: 95,
    protein: 7,
    carbs: 5,
    fats: 4,
    fiber: 1,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['dairy-free', 'vegan', 'calcium', 'protein'],
    servingSize: '1 cup (250ml)',
  },
  {
    id: 'sf-089',
    name: 'Bandung',
    localName: '萬隆飲料',
    category: 'beverage',
    cuisine: 'malaysian',
    calories: 140,
    protein: 3,
    carbs: 28,
    fats: 2,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: false,
    tags: ['sweet', 'rose', 'milky'],
    servingSize: '1 cup (300ml)',
  },
  {
    id: 'sf-090',
    name: 'Teh Tarik',
    localName: '拉茶',
    category: 'beverage',
    cuisine: 'singapore',
    calories: 135,
    protein: 3,
    carbs: 20,
    fats: 5,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: false,
    tags: ['classic', 'milky', 'caffeine'],
    servingSize: '1 cup (300ml)',
  },
  {
    id: 'sf-091',
    name: 'Milo Dinosaur',
    localName: '美禄恐龙',
    category: 'beverage',
    cuisine: 'singapore',
    calories: 200,
    protein: 8,
    carbs: 32,
    fats: 5,
    fiber: 1,
    isQuickPrep: true,
    isHealthyOption: false,
    tags: ['chocolate', 'sweet', 'classic', 'malted'],
    servingSize: '1 cup (400ml)',
  },
  {
    id: 'sf-092',
    name: 'Lemon Barley Water',
    localName: '柠檬薏米水',
    category: 'beverage',
    cuisine: 'singapore',
    calories: 90,
    protein: 1,
    carbs: 22,
    fats: 0,
    fiber: 1,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-calorie', 'refreshing', 'vitamin-c'],
    servingSize: '1 cup (300ml)',
  },
  {
    id: 'sf-093',
    name: 'Sugar Cane Juice',
    localName: '甘蔗汁',
    category: 'beverage',
    cuisine: 'singapore',
    calories: 180,
    protein: 0,
    carbs: 46,
    fats: 0,
    fiber: 0,
    isQuickPrep: true,
    isHealthyOption: false,
    tags: ['sweet', 'refreshing', 'traditional'],
    servingSize: '1 cup (300ml)',
  },

  // ── Snacks / Desserts ──────────────────────────────────────────
  {
    id: 'sf-094',
    name: 'Ice Kachang',
    localName: '红豆冰',
    category: 'snack',
    cuisine: 'singapore',
    calories: 280,
    protein: 4,
    carbs: 62,
    fats: 2,
    fiber: 3,
    isQuickPrep: true,
    isHealthyOption: false,
    tags: ['sweet', 'cold', 'dessert', 'classic'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-095',
    name: 'Chendol',
    localName: '煎蕊',
    category: 'snack',
    cuisine: 'singapore',
    calories: 320,
    protein: 4,
    carbs: 58,
    fats: 8,
    fiber: 2,
    isQuickPrep: true,
    isHealthyOption: false,
    tags: ['sweet', 'coconut', 'dessert', 'classic'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-096',
    name: 'Tau Huay (Silken Tofu)',
    localName: '豆花',
    category: 'snack',
    cuisine: 'chinese',
    calories: 160,
    protein: 10,
    carbs: 22,
    fats: 4,
    fiber: 1,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-calorie', 'vegetarian', 'calcium', 'classic'],
    servingSize: '1 bowl',
  },
  {
    id: 'sf-097',
    name: 'Banana (1)',
    category: 'snack',
    cuisine: 'western',
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fats: 0.4,
    fiber: 3,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['potassium', 'pre-workout', 'natural-sugar'],
    servingSize: '1 medium',
  },
  {
    id: 'sf-098',
    name: 'Mixed Nuts (Handful)',
    category: 'snack',
    cuisine: 'western',
    calories: 170,
    protein: 6,
    carbs: 6,
    fats: 15,
    fiber: 2,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['healthy-fats', 'omega-3', 'keto-snack'],
    servingSize: '30g',
  },
  {
    id: 'sf-099',
    name: 'Rice Crackers',
    localName: '米饼',
    category: 'snack',
    cuisine: 'chinese',
    calories: 140,
    protein: 2,
    carbs: 22,
    fats: 5,
    fiber: 1,
    isQuickPrep: true,
    isHealthyOption: false,
    tags: ['light', 'crispy', 'quick'],
    servingSize: '1 pack',
  },
  {
    id: 'sf-100',
    name: 'Seaweed Snacks',
    category: 'snack',
    cuisine: 'japanese',
    calories: 30,
    protein: 2,
    carbs: 2,
    fats: 2,
    fiber: 2,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-calorie', 'iodine', 'crispy', 'vegan'],
    servingSize: '1 pack',
  },

  // ── Carbohydrate Sources ───────────────────────────────────────
  {
    id: 'sf-101',
    name: 'Steamed White Rice',
    localName: '白饭',
    category: 'carb',
    cuisine: 'chinese',
    calories: 240,
    protein: 5,
    carbs: 52,
    fats: 0.5,
    fiber: 1,
    isQuickPrep: true,
    isHealthyOption: false,
    tags: ['gluten-free', 'staple'],
    servingSize: '1 bowl (150g)',
  },
  {
    id: 'sf-102',
    name: 'Brown Rice',
    localName: '糙米饭',
    category: 'carb',
    cuisine: 'chinese',
    calories: 220,
    protein: 5,
    carbs: 46,
    fats: 1.8,
    fiber: 4,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['high-fiber', 'low-gi', 'gluten-free'],
    servingSize: '1 bowl (150g)',
  },
  {
    id: 'sf-103',
    name: 'Rice Noodles (Kway Teow)',
    localName: '粿条',
    category: 'carb',
    cuisine: 'chinese',
    calories: 200,
    protein: 4,
    carbs: 44,
    fats: 1,
    fiber: 1,
    isQuickPrep: true,
    isHealthyOption: false,
    tags: ['gluten-free', 'staple'],
    servingSize: '1 serving (150g)',
  },
  {
    id: 'sf-104',
    name: 'Egg Noodles (Mee Kia)',
    localName: '面仔',
    category: 'carb',
    cuisine: 'chinese',
    calories: 280,
    protein: 10,
    carbs: 50,
    fats: 4,
    fiber: 2,
    isQuickPrep: true,
    isHealthyOption: false,
    tags: ['egg-noodles', 'staple'],
    servingSize: '1 serving (150g)',
  },
  {
    id: 'sf-105',
    name: 'Wholemeal Bread (2 slices)',
    category: 'carb',
    cuisine: 'western',
    calories: 160,
    protein: 8,
    carbs: 28,
    fats: 2,
    fiber: 6,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-fiber', 'wholegrain'],
    servingSize: '2 slices',
  },
  {
    id: 'sf-106',
    name: 'Oats (Cooked)',
    category: 'carb',
    cuisine: 'western',
    calories: 150,
    protein: 5,
    carbs: 27,
    fats: 3,
    fiber: 4,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-fiber', 'low-gi', 'beta-glucan'],
    servingSize: '1 bowl (40g dry)',
  },
  {
    id: 'sf-107',
    name: 'Sweet Potato (Steamed)',
    localName: '番薯',
    category: 'carb',
    cuisine: 'chinese',
    calories: 130,
    protein: 2,
    carbs: 28,
    fats: 0.2,
    fiber: 4,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-fat', 'vitamin-a', 'low-gi'],
    servingSize: '1 medium (150g)',
  },

  // ── Vegetables ─────────────────────────────────────────────────
  {
    id: 'sf-108',
    name: 'Steamed Broccoli',
    category: 'vegetable',
    cuisine: 'chinese',
    calories: 55,
    protein: 4,
    carbs: 10,
    fats: 0.5,
    fiber: 4,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-calorie', 'vitamin-c', 'fiber-rich'],
    servingSize: '1 cup (150g)',
  },
  {
    id: 'sf-109',
    name: 'Bok Choy (Steamed)',
    localName: '小白菜',
    category: 'vegetable',
    cuisine: 'chinese',
    calories: 25,
    protein: 2,
    carbs: 4,
    fats: 0.2,
    fiber: 2,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-calorie', 'calcium', 'vitamin-k'],
    servingSize: '1 cup (150g)',
  },
  {
    id: 'sf-110',
    name: 'Cucumber Salad',
    category: 'vegetable',
    cuisine: 'chinese',
    calories: 35,
    protein: 1,
    carbs: 6,
    fats: 1,
    fiber: 2,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-calorie', 'hydrating', 'refreshing'],
    servingSize: '1 cup',
  },
  {
    id: 'sf-111',
    name: 'Tomato & Egg Stir-fry',
    localName: '番茄炒蛋',
    category: 'home-cooked',
    cuisine: 'chinese',
    calories: 220,
    protein: 14,
    carbs: 16,
    fats: 12,
    fiber: 3,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['high-protein', 'lycopene', 'quick'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-112',
    name: 'Spinach with Garlic',
    category: 'vegetable',
    cuisine: 'chinese',
    calories: 65,
    protein: 4,
    carbs: 8,
    fats: 3,
    fiber: 4,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-calorie', 'iron', 'vitamin-a'],
    servingSize: '1 cup (150g)',
  },
  {
    id: 'sf-113',
    name: 'Bean Sprouts Stir-fry',
    localName: '炒豆芽',
    category: 'vegetable',
    cuisine: 'chinese',
    calories: 55,
    protein: 4,
    carbs: 8,
    fats: 2,
    fiber: 3,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['low-calorie', 'crunchy', 'quick'],
    servingSize: '1 cup (150g)',
  },

  // ── Thai ───────────────────────────────────────────────────────
  {
    id: 'sf-114',
    name: 'Pad Thai',
    localName: 'ผัดไทย',
    category: 'restaurant',
    cuisine: 'thai',
    calories: 540,
    protein: 22,
    carbs: 72,
    fats: 18,
    fiber: 4,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['spicy', 'peanut', 'sweet-sour', 'classic'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-115',
    name: 'Green Curry Chicken',
    localName: 'แกงเขียวหวาน',
    category: 'restaurant',
    cuisine: 'thai',
    calories: 480,
    protein: 30,
    carbs: 16,
    fats: 34,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['spicy', 'coconut', 'halal-option', 'aromatic'],
    servingSize: '1 bowl with rice',
  },
  {
    id: 'sf-116',
    name: 'Tom Yum Soup',
    localName: 'ต้มยำ',
    category: 'restaurant',
    cuisine: 'thai',
    calories: 140,
    protein: 16,
    carbs: 10,
    fats: 4,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['spicy', 'sour', 'low-calorie', 'seafood'],
    servingSize: '1 bowl',
  },

  // ── Indian ─────────────────────────────────────────────────────
  {
    id: 'sf-117',
    name: 'Butter Chicken',
    localName: 'मक्खन मुर्ग़',
    category: 'restaurant',
    cuisine: 'indian',
    calories: 580,
    protein: 34,
    carbs: 22,
    fats: 38,
    fiber: 3,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['high-protein', 'creamy', 'halal', 'rich'],
    servingSize: '1 serving with naan',
  },
  {
    id: 'sf-118',
    name: 'Vegetable Biryani',
    localName: 'सब्जी बिरयानी',
    category: 'restaurant',
    cuisine: 'indian',
    calories: 480,
    protein: 12,
    carbs: 72,
    fats: 16,
    fiber: 6,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['vegetarian', 'aromatic', 'spicy', 'halal'],
    servingSize: '1 plate',
  },
  {
    id: 'sf-119',
    name: 'Tandoori Chicken',
    localName: 'तंदूरी चिकन',
    category: 'restaurant',
    cuisine: 'indian',
    calories: 320,
    protein: 42,
    carbs: 6,
    fats: 14,
    fiber: 1,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['high-protein', 'low-carb', 'halal', 'smoky'],
    servingSize: '1/2 chicken',
  },
  {
    id: 'sf-120',
    name: 'Masala Dosa',
    localName: 'मसाला डोसा',
    category: 'hawker',
    cuisine: 'indian',
    calories: 380,
    protein: 8,
    carbs: 62,
    fats: 12,
    fiber: 5,
    isQuickPrep: false,
    isHealthyOption: false,
    tags: ['vegetarian', 'fermented', 'crispy', 'halal'],
    servingSize: '1 dosa',
  },
  {
    id: 'sf-121',
    name: 'Chapati (2 pieces)',
    localName: 'रोटी',
    category: 'carb',
    cuisine: 'indian',
    calories: 200,
    protein: 6,
    carbs: 38,
    fats: 4,
    fiber: 4,
    isQuickPrep: true,
    isHealthyOption: true,
    tags: ['wholegrain', 'low-fat', 'halal'],
    servingSize: '2 pieces',
  },
  {
    id: 'sf-122',
    name: 'Chicken Tikka',
    localName: 'चिकन टिक्का',
    category: 'restaurant',
    cuisine: 'indian',
    calories: 280,
    protein: 36,
    carbs: 8,
    fats: 12,
    fiber: 2,
    isQuickPrep: false,
    isHealthyOption: true,
    tags: ['high-protein', 'low-carb', 'halal', 'smoky'],
    servingSize: '4 pieces',
  },
];

/* ================================================================
   Helper Functions
   ================================================================ */

/**
 * Search foods by query string across name, localName, and tags.
 * Optionally filter by category, cuisine, quick-prep, and healthy flags.
 */
export function searchFoods(
  query: string,
  filters?: Partial<{
    category: FoodCategory;
    cuisine: CuisineType;
    isQuickPrep: boolean;
    isHealthyOption: boolean;
  }>
): FoodItem[] {
  const q = query.toLowerCase().trim();
  let results = SINGAPORE_FOOD_DATABASE.filter((item) => {
    const matchesQuery =
      !q ||
      item.name.toLowerCase().includes(q) ||
      (item.localName && item.localName.toLowerCase().includes(q)) ||
      item.tags.some((t) => t.toLowerCase().includes(q));

    if (!matchesQuery) return false;

    if (filters?.category && item.category !== filters.category) return false;
    if (filters?.cuisine && item.cuisine !== filters.cuisine) return false;
    if (filters?.isQuickPrep !== undefined && item.isQuickPrep !== filters.isQuickPrep)
      return false;
    if (filters?.isHealthyOption !== undefined && item.isHealthyOption !== filters.isHealthyOption)
      return false;

    return true;
  });

  return results;
}

/** Return all foods that have a specific tag. */
export function getFoodsByTag(tag: string): FoodItem[] {
  const t = tag.toLowerCase();
  return SINGAPORE_FOOD_DATABASE.filter((item) =>
    item.tags.some((it) => it.toLowerCase().includes(t))
  );
}

/** Return all quick-prep meals (under 15 min). */
export function getQuickPrepMeals(): FoodItem[] {
  return SINGAPORE_FOOD_DATABASE.filter((item) => item.isQuickPrep);
}

/** Return all foods marked as healthy options. */
export function getHealthyOptions(): FoodItem[] {
  return SINGAPORE_FOOD_DATABASE.filter((item) => item.isHealthyOption);
}

/** Get a single food item by its ID. */
export function getFoodById(id: string): FoodItem | undefined {
  return SINGAPORE_FOOD_DATABASE.find((item) => item.id === id);
}

/** Return foods grouped by category. */
export function getFoodsByCategory(category: FoodCategory): FoodItem[] {
  return SINGAPORE_FOOD_DATABASE.filter((item) => item.category === category);
}

/** Return foods grouped by cuisine. */
export function getFoodsByCuisine(cuisine: CuisineType): FoodItem[] {
  return SINGAPORE_FOOD_DATABASE.filter((item) => item.cuisine === cuisine);
}

/**
 * Find food alternatives with similar calorie range but different macros.
 * Used for the "smart swap" feature.
 */
export function findAlternatives(
  foodId: string,
  calorieTolerance = 100
): FoodItem[] {
  const source = getFoodById(foodId);
  if (!source) return [];

  const minCal = source.calories - calorieTolerance;
  const maxCal = source.calories + calorieTolerance;

  return SINGAPORE_FOOD_DATABASE.filter((item) => {
    if (item.id === foodId) return false;
    if (item.calories < minCal || item.calories > maxCal) return false;
    // Prefer different macro profile
    const proteinDiff = Math.abs(item.protein - source.protein);
    return proteinDiff >= 5;
  }).sort((a, b) => a.calories - b.calories);
}
