/**
 * AzFIT Programs Library — 84 programs imported from Excel
 * Source: AzFIT PROGRAMS LIBRARY.xlsx
 */

export interface ProgramLibraryData {
  programId: string;
  name: string;
  goal: string;
  durationWeeks: number;
  frequencyPerWeek: number;
  difficulty: string;
  method: string;
  equipmentNeeded: string;
  programStructure: string;
  progressionModel: string;
  nutritionNotes: string;
  safetyNotes: string;
  timesUsed: number;
  avgAdherencePct: number;
  revenueHkd: number;
  clientSatisfaction: number;
  status: string;
  category: string;
  description: string;
}

export const PROGRAMS_LIBRARY: ProgramLibraryData[] = [
  {
    programId: 'PRO001',
    name: "German Body Composition (GBC)",
    goal: 'Fat Loss',
    durationWeeks: 6,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'GBC',
    equipmentNeeded: "Dumbbells, Barbells, Machines",
    programStructure: "Upper/lower superset pairs, 60s rest",
    progressionModel: "Increase load 5% weekly",
    nutritionNotes: "Moderate carbs post-workout",
    safetyNotes: "Avoid failure on compound lifts",
    timesUsed: 12,
    avgAdherencePct: 82.0,
    revenueHkd: 115200.0,
    clientSatisfaction: 4.7,
    status: 'Active',
    category: 'Strength Training',
    description: "Upper/lower superset pairs, 60s rest for body recomposition",
  },
  {
    programId: 'PRO002',
    name: "StrongLifts 5x5",
    goal: 'Strength',
    durationWeeks: 12,
    frequencyPerWeek: 3,
    difficulty: 'Beginner',
    method: '5x5',
    equipmentNeeded: "Squat Rack, Barbell, Bench",
    programStructure: "5 sets x 5 reps, A/B rotation",
    progressionModel: "Add 2.5kg per workout",
    nutritionNotes: "High protein, caloric surplus",
    safetyNotes: "Master form before load",
    timesUsed: 8,
    avgAdherencePct: 78.0,
    revenueHkd: 105600.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Strength Training',
    description: "Foundational strength program with progressive overload",
  },
  {
    programId: 'PRO003',
    name: "Push/Pull/Legs (PPL)",
    goal: 'Hypertrophy',
    durationWeeks: 8,
    frequencyPerWeek: 6,
    difficulty: 'Advanced',
    method: 'PPL',
    equipmentNeeded: "Full Gym Access",
    programStructure: "6-day split: push/pull/legs x2",
    progressionModel: "Add volume or weight",
    nutritionNotes: "Protein 2g/kg bodyweight",
    safetyNotes: "Manage weekly volume",
    timesUsed: 15,
    avgAdherencePct: 85.0,
    revenueHkd: 198000.0,
    clientSatisfaction: 4.8,
    status: 'Active',
    category: 'Strength Training',
    description: "Advanced hypertrophy + strength program, 6-day split",
  },
  {
    programId: 'PRO004',
    name: "Upper/Lower Split",
    goal: 'General Fitness',
    durationWeeks: 8,
    frequencyPerWeek: 4,
    difficulty: 'All Levels',
    method: 'Upper/Lower',
    equipmentNeeded: "Barbells, Dumbbells, Machines",
    programStructure: "4-day: 2 upper, 2 lower",
    progressionModel: "Progressive overload",
    nutritionNotes: "Moderate surplus",
    safetyNotes: "Rotate heavy and light days",
    timesUsed: 10,
    avgAdherencePct: 80.0,
    revenueHkd: 96000.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Strength Training',
    description: "Balanced physique program for all fitness levels",
  },
  {
    programId: 'PRO005',
    name: "5/3/1 Wendler",
    goal: 'Strength',
    durationWeeks: 12,
    frequencyPerWeek: 4,
    difficulty: 'Advanced',
    method: '5/3/1',
    equipmentNeeded: "Squat Rack, Bench, Deadlift Bar",
    programStructure: "Main lift + assistance",
    progressionModel: "Monthly TM increase",
    nutritionNotes: "High calories, protein",
    safetyNotes: "Use training max, not true 1RM",
    timesUsed: 5,
    avgAdherencePct: 75.0,
    revenueHkd: 66000.0,
    clientSatisfaction: 4.4,
    status: 'Active',
    category: 'Strength Training',
    description: "Maximal strength program with monthly training max increases",
  },
  {
    programId: 'PRO006',
    name: "Westside Barbell",
    goal: 'Powerlifting',
    durationWeeks: 16,
    frequencyPerWeek: 4,
    difficulty: 'Elite',
    method: 'Conjugate',
    equipmentNeeded: "Full Powerlifting Gym",
    programStructure: "Max effort + dynamic effort",
    progressionModel: "Conjugate method rotation",
    nutritionNotes: "Caloric surplus + creatine",
    safetyNotes: "Specialized equipment needed",
    timesUsed: 3,
    avgAdherencePct: 82.0,
    revenueHkd: 39600.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Strength Training',
    description: "Elite powerlifting total program using conjugate method",
  },
  {
    programId: 'PRO007',
    name: "DUP (Daily Undulating Periodization)",
    goal: 'Strength + Size',
    durationWeeks: 8,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'DUP',
    equipmentNeeded: "Full Gym",
    programStructure: "Hypertrophy/strength/power days",
    progressionModel: "Wave loading weekly",
    nutritionNotes: "Carbs around training",
    safetyNotes: "Auto-regulate daily",
    timesUsed: 6,
    avgAdherencePct: 80.0,
    revenueHkd: 57600.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Strength Training',
    description: "Daily undulating periodization for strength and size",
  },
  {
    programId: 'PRO008',
    name: "PHAT (Power Hypertrophy Adaptive Training)",
    goal: 'Size + Strength',
    durationWeeks: 12,
    frequencyPerWeek: 5,
    difficulty: 'Advanced',
    method: 'PHAT',
    equipmentNeeded: "Full Gym",
    programStructure: "2 power days + 3 hypertrophy",
    progressionModel: "Add sets then weight",
    nutritionNotes: "Lean bulk macros",
    safetyNotes: "Rest days mandatory",
    timesUsed: 4,
    avgAdherencePct: 83.0,
    revenueHkd: 52800.0,
    clientSatisfaction: 4.7,
    status: 'Active',
    category: 'Strength Training',
    description: "Power Hypertrophy Adaptive Training for advanced lifters",
  },
  {
    programId: 'PRO009',
    name: "PHUL (Power Hypertrophy Upper Lower)",
    goal: 'Power + Aesthetics',
    durationWeeks: 8,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'PHUL',
    equipmentNeeded: "Full Gym",
    programStructure: "4-day: power upper/lower, hypertrophy upper/lower",
    progressionModel: "Double progression",
    nutritionNotes: "Moderate surplus",
    safetyNotes: "Don't skip power days",
    timesUsed: 7,
    avgAdherencePct: 81.0,
    revenueHkd: 67200.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Strength Training',
    description: "Power + aesthetics blend with 4-day upper/lower split",
  },
  {
    programId: 'PRO010',
    name: "GVT (German Volume Training)",
    goal: 'Extreme Hypertrophy',
    durationWeeks: 6,
    frequencyPerWeek: 5,
    difficulty: 'Advanced',
    method: 'GVT',
    equipmentNeeded: "Machines, Barbells",
    programStructure: "10x10 on major lifts",
    progressionModel: "Increase weight after 6 weeks",
    nutritionNotes: "High calories essential",
    safetyNotes: "DOMS will be severe",
    timesUsed: 5,
    avgAdherencePct: 77.0,
    revenueHkd: 39600.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Strength Training',
    description: "Extreme hypertrophy with 10x10 on major compound lifts",
  },
  {
    programId: 'PRO011',
    name: "HIIT Cardio",
    goal: 'Rapid Fat Loss',
    durationWeeks: 4,
    frequencyPerWeek: 3,
    difficulty: 'All Levels',
    method: 'HIIT',
    equipmentNeeded: "Treadmill, Bike, Rower",
    programStructure: "30s max / 30s rest intervals",
    progressionModel: "Reduce rest by 5s weekly",
    nutritionNotes: "Moderate deficit",
    safetyNotes: "Warm up thoroughly",
    timesUsed: 20,
    avgAdherencePct: 70.0,
    revenueHkd: 48000.0,
    clientSatisfaction: 4.2,
    status: 'Active',
    category: 'Weight Loss',
    description: "High-intensity interval training for rapid fat loss",
  },
  {
    programId: 'PRO012',
    name: "MetCon (Metabolic Conditioning)",
    goal: 'Fat Burn + Endurance',
    durationWeeks: 6,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'MetCon',
    equipmentNeeded: "Kettlebells, Ropes, Sleds",
    programStructure: "Compound circuits, minimal rest",
    progressionModel: "Decrease rest time",
    nutritionNotes: "Low-carb on rest days",
    safetyNotes: "Watch for overreaching",
    timesUsed: 6,
    avgAdherencePct: 76.0,
    revenueHkd: 57600.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Weight Loss',
    description: "Metabolic conditioning with compound circuits and minimal rest",
  },
  {
    programId: 'PRO013',
    name: "Tabata Protocol",
    goal: 'Anaerobic Capacity',
    durationWeeks: 4,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'Tabata',
    equipmentNeeded: "Bike, Rower, Bodyweight",
    programStructure: "20s on / 10s off x 8 rounds",
    progressionModel: "Add rounds or intensity",
    nutritionNotes: "Time meals around sessions",
    safetyNotes: "Not for beginners daily",
    timesUsed: 8,
    avgAdherencePct: 74.0,
    revenueHkd: 38400.0,
    clientSatisfaction: 4.3,
    status: 'Active',
    category: 'Weight Loss',
    description: "Tabata protocol for anaerobic capacity and fat loss",
  },
  {
    programId: 'PRO014',
    name: "Circuit Training",
    goal: 'Full-Body Fat Loss',
    durationWeeks: 6,
    frequencyPerWeek: 3,
    difficulty: 'All Levels',
    method: 'Circuit',
    equipmentNeeded: "Machines, Free Weights, Cardio",
    programStructure: "8-12 stations, 45s each",
    progressionModel: "Increase station difficulty",
    nutritionNotes: "Moderate deficit",
    safetyNotes: "Rotate stations to avoid fatigue",
    timesUsed: 14,
    avgAdherencePct: 72.0,
    revenueHkd: 67200.0,
    clientSatisfaction: 4.4,
    status: 'Active',
    category: 'Weight Loss',
    description: "Full-body circuit training with 8-12 stations",
  },
  {
    programId: 'PRO015',
    name: "EMOM (Every Minute On the Minute)",
    goal: 'Work Capacity',
    durationWeeks: 4,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'EMOM',
    equipmentNeeded: "Barbells, Kettlebells, Pull-Up Bar",
    programStructure: "Perform reps within 60s, rest remainder",
    progressionModel: "Add reps or weight",
    nutritionNotes: "Protein-focused meals",
    safetyNotes: "Start conservative",
    timesUsed: 5,
    avgAdherencePct: 78.0,
    revenueHkd: 48000.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Weight Loss',
    description: "Every minute on the minute for work capacity and fat loss",
  },
  {
    programId: 'PRO016',
    name: "AMRAP (As Many Rounds As Possible)",
    goal: 'Density + Conditioning',
    durationWeeks: 4,
    frequencyPerWeek: 3,
    difficulty: 'Intermediate',
    method: 'AMRAP',
    equipmentNeeded: "Mixed Equipment",
    programStructure: "Complete rounds in set time",
    progressionModel: "Reduce time or add load",
    nutritionNotes: "Moderate carbs",
    safetyNotes: "Track form degradation",
    timesUsed: 7,
    avgAdherencePct: 75.0,
    revenueHkd: 42000.0,
    clientSatisfaction: 4.4,
    status: 'Active',
    category: 'Weight Loss',
    description: "Density training: as many rounds as possible in set time",
  },
  {
    programId: 'PRO017',
    name: "Bodyweight Burn",
    goal: 'Fat Loss No Equipment',
    durationWeeks: 6,
    frequencyPerWeek: 4,
    difficulty: 'Beginner',
    method: 'Bodyweight',
    equipmentNeeded: "None (Bodyweight)",
    programStructure: "Push-ups, squats, burpees, planks",
    progressionModel: "Increase tempo or reps",
    nutritionNotes: "Caloric deficit critical",
    safetyNotes: "Progress gradually",
    timesUsed: 25,
    avgAdherencePct: 72.0,
    revenueHkd: 72000.0,
    clientSatisfaction: 4.3,
    status: 'Active',
    category: 'Weight Loss',
    description: "Bodyweight-only fat loss program for beginners/home users",
  },
  {
    programId: 'PRO018',
    name: "Kettlebell Fat Loss",
    goal: 'Dynamic Fat Burning',
    durationWeeks: 6,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'Kettlebell',
    equipmentNeeded: "Kettlebells, Mat",
    programStructure: "Swings, cleans, snatches, get-ups",
    progressionModel: "Increase bell size",
    nutritionNotes: "High protein, moderate carbs",
    safetyNotes: "Learn hip hinge first",
    timesUsed: 9,
    avgAdherencePct: 79.0,
    revenueHkd: 43200.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Weight Loss',
    description: "Kettlebell-focused dynamic fat burning program",
  },
  {
    programId: 'PRO019',
    name: "Hyrox Training",
    goal: 'Hybrid Race Prep',
    durationWeeks: 12,
    frequencyPerWeek: 5,
    difficulty: 'Intermediate-Advanced',
    method: 'Hyrox',
    equipmentNeeded: "Ski Erg, Rower, Sled, Wall Balls",
    programStructure: "Running + functional stations",
    progressionModel: "Add distance or load",
    nutritionNotes: "High carbs for sessions",
    safetyNotes: "Practice transitions",
    timesUsed: 4,
    avgAdherencePct: 84.0,
    revenueHkd: 52800.0,
    clientSatisfaction: 4.7,
    status: 'Active',
    category: 'Specific Programs',
    description: "Hybrid race preparation combining running and functional fitness",
  },
  {
    programId: 'PRO020',
    name: "CrossFit WOD",
    goal: 'General Fitness',
    durationWeeks: 12,
    frequencyPerWeek: 5,
    difficulty: 'All Levels',
    method: 'CrossFit',
    equipmentNeeded: "Full CrossFit Box",
    programStructure: "Varied functional movements",
    progressionModel: "Benchmark WOD comparison",
    nutritionNotes: "Zone or balanced macros",
    safetyNotes: "Scale appropriately",
    timesUsed: 18,
    avgAdherencePct: 76.0,
    revenueHkd: 86400.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Specific Programs',
    description: "CrossFit WOD program for general physical preparedness",
  },
  {
    programId: 'PRO021',
    name: "Marathon Prep",
    goal: 'Marathon Completion',
    durationWeeks: 16,
    frequencyPerWeek: 5,
    difficulty: 'Intermediate',
    method: 'Running',
    equipmentNeeded: "Shoes, GPS Watch, Foam Roller",
    programStructure: "Progressive mileage build",
    progressionModel: "10% weekly mileage rule",
    nutritionNotes: "Carb loading before long runs",
    safetyNotes: "Replace shoes every 500km",
    timesUsed: 3,
    avgAdherencePct: 88.0,
    revenueHkd: 39600.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Specific Programs',
    description: "Progressive marathon training with long run build-up",
  },
  {
    programId: 'PRO022',
    name: "Half Marathon Ready",
    goal: '21.1km Race Prep',
    durationWeeks: 12,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'Running',
    equipmentNeeded: "Running Shoes, Watch",
    programStructure: "Long run + tempo + intervals",
    progressionModel: "Increase long run by 1km",
    nutritionNotes: "Carbs pre-run",
    safetyNotes: "Taper last 2 weeks",
    timesUsed: 5,
    avgAdherencePct: 85.0,
    revenueHkd: 48000.0,
    clientSatisfaction: 4.7,
    status: 'Active',
    category: 'Specific Programs',
    description: "Half marathon preparation for recreational runners",
  },
  {
    programId: 'PRO023',
    name: "10K Ready",
    goal: '10km Race Prep',
    durationWeeks: 8,
    frequencyPerWeek: 4,
    difficulty: 'Beginner',
    method: 'Running',
    equipmentNeeded: "Running Shoes",
    programStructure: "3 easy + 1 tempo + 1 long",
    progressionModel: "Speed up tempo pace",
    nutritionNotes: "Balanced diet",
    safetyNotes: "Rest on hard days",
    timesUsed: 8,
    avgAdherencePct: 82.0,
    revenueHkd: 38400.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Specific Programs',
    description: "10K race preparation for beginner runners",
  },
  {
    programId: 'PRO024',
    name: "Triathlon Base",
    goal: 'Foundation for Triathlon',
    durationWeeks: 12,
    frequencyPerWeek: 5,
    difficulty: 'Intermediate',
    method: 'Triathlon',
    equipmentNeeded: "Bike, Pool Access, Shoes",
    programStructure: "Swim/bike/run each week",
    progressionModel: "10% volume increase",
    nutritionNotes: "High carbs during training",
    safetyNotes: "Brick sessions essential",
    timesUsed: 2,
    avgAdherencePct: 86.0,
    revenueHkd: 31200.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Specific Programs',
    description: "Foundation triathlon program with swim/bike/run balance",
  },
  {
    programId: 'PRO025',
    name: "Sprint Triathlon",
    goal: '750m/20km/5km Race',
    durationWeeks: 8,
    frequencyPerWeek: 5,
    difficulty: 'Beginner',
    method: 'Triathlon',
    equipmentNeeded: "Bike, Pool, Running Shoes",
    programStructure: "Short but intense sessions",
    progressionModel: "Increase intensity",
    nutritionNotes: "Practice race nutrition",
    safetyNotes: "Race-pace intervals",
    timesUsed: 3,
    avgAdherencePct: 83.0,
    revenueHkd: 28800.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Specific Programs',
    description: "Sprint triathlon preparation for beginner triathletes",
  },
  {
    programId: 'PRO026',
    name: "Rugby Strength",
    goal: 'Contact Sport Power',
    durationWeeks: 8,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'Sport-Specific',
    equipmentNeeded: "Power Rack, Prowler, Sled",
    programStructure: "Heavy compounds + tackling drills",
    progressionModel: "5% load increase",
    nutritionNotes: "High protein, creatine",
    safetyNotes: "Neck training included",
    timesUsed: 2,
    avgAdherencePct: 80.0,
    revenueHkd: 19200.0,
    clientSatisfaction: 4.4,
    status: 'Active',
    category: 'Sports-Specific',
    description: "Rugby strength and power program with contact prep",
  },
  {
    programId: 'PRO027',
    name: "Soccer Fitness",
    goal: 'Pitch Endurance',
    durationWeeks: 8,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'Sport-Specific',
    equipmentNeeded: "Pitch, Cones, Agility Ladder",
    programStructure: "Sprints, changes of direction, ball work",
    progressionModel: "Increase sprint distance",
    nutritionNotes: "Carb-focused match prep",
    safetyNotes: "Ankle/knee prehab",
    timesUsed: 4,
    avgAdherencePct: 78.0,
    revenueHkd: 38400.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Sports-Specific',
    description: "Soccer-specific endurance and agility program",
  },
  {
    programId: 'PRO028',
    name: "Basketball Plyo",
    goal: 'Vertical Jump + Power',
    durationWeeks: 8,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'Sport-Specific',
    equipmentNeeded: "Plyo Boxes, Courts",
    programStructure: "Jumps, bounds, reactive jumps",
    progressionModel: "Increase box height",
    nutritionNotes: "Moderate surplus",
    safetyNotes: "Land softly always",
    timesUsed: 3,
    avgAdherencePct: 81.0,
    revenueHkd: 28800.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Sports-Specific',
    description: "Plyometric training for basketball vertical jump and power",
  },
  {
    programId: 'PRO029',
    name: "BJJ Strength",
    goal: 'Grappling Strength',
    durationWeeks: 8,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'Sport-Specific',
    equipmentNeeded: "Rings, Ropes, Kettlebells",
    programStructure: "Pulling strength, grip, core",
    progressionModel: "Increase pull-up reps",
    nutritionNotes: "Moderate surplus",
    safetyNotes: "Neck and grip prehab",
    timesUsed: 4,
    avgAdherencePct: 84.0,
    revenueHkd: 38400.0,
    clientSatisfaction: 4.7,
    status: 'Active',
    category: 'Sports-Specific',
    description: "Brazilian Jiu-Jitsu strength program with grip and pulling focus",
  },
  {
    programId: 'PRO030',
    name: "Summer Shred",
    goal: 'Beach-Ready Physique',
    durationWeeks: 8,
    frequencyPerWeek: 5,
    difficulty: 'All Levels',
    method: 'Seasonal',
    equipmentNeeded: "Full Gym or Home",
    programStructure: "High frequency, moderate volume",
    progressionModel: "Increase cardio weekly",
    nutritionNotes: "Aggressive deficit",
    safetyNotes: "Don't crash diet",
    timesUsed: 22,
    avgAdherencePct: 74.0,
    revenueHkd: 105600.0,
    clientSatisfaction: 4.4,
    status: 'Active',
    category: 'Seasonal',
    description: "Summer physique program with high frequency and moderate volume",
  },
  {
    programId: 'PRO031',
    name: "Winter Bulk",
    goal: 'Maximize Muscle Gain',
    durationWeeks: 12,
    frequencyPerWeek: 5,
    difficulty: 'Intermediate',
    method: 'Seasonal',
    equipmentNeeded: "Full Gym",
    programStructure: "High volume + surplus",
    progressionModel: "Add weight then volume",
    nutritionNotes: "500+ surplus",
    safetyNotes: "Minimize fat gain",
    timesUsed: 12,
    avgAdherencePct: 80.0,
    revenueHkd: 158400.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Seasonal',
    description: "Winter muscle building program with high volume and caloric surplus",
  },
  {
    programId: 'PRO032',
    name: "New Year Reset",
    goal: 'Rebuild Habits',
    durationWeeks: 6,
    frequencyPerWeek: 4,
    difficulty: 'All Levels',
    method: 'Seasonal',
    equipmentNeeded: "Gym or Home",
    programStructure: "Full-body frequency",
    progressionModel: "Add days then intensity",
    nutritionNotes: "Clean eating focus",
    safetyNotes: "Sustainable changes only",
    timesUsed: 30,
    avgAdherencePct: 68.0,
    revenueHkd: 72000.0,
    clientSatisfaction: 4.3,
    status: 'Active',
    category: 'Seasonal',
    description: "Habit rebuilding program for New Year fitness goals",
  },
  {
    programId: 'PRO033',
    name: "Beach Body",
    goal: 'Aesthetic Peak',
    durationWeeks: 6,
    frequencyPerWeek: 5,
    difficulty: 'Intermediate',
    method: 'Seasonal',
    equipmentNeeded: "Full Gym",
    programStructure: "High volume + cardio finishers",
    progressionModel: "Increase density",
    nutritionNotes: "Carb cycling option",
    safetyNotes: "Tan + posing practice",
    timesUsed: 18,
    avgAdherencePct: 73.0,
    revenueHkd: 86400.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Seasonal',
    description: "Aesthetic peak program for beach season with carb cycling",
  },
  {
    programId: 'PRO034',
    name: "Charles Poliquin GBC",
    goal: 'Body Recomposition',
    durationWeeks: 6,
    frequencyPerWeek: 4,
    difficulty: 'Advanced',
    method: 'Performance',
    equipmentNeeded: "Machines, Dumbbells",
    programStructure: "6x6 supersets, 60s rest",
    progressionModel: "Reduce rest or increase load",
    nutritionNotes: "Low carb AM, high carb PM",
    safetyNotes: "Blood flow restriction optional",
    timesUsed: 4,
    avgAdherencePct: 79.0,
    revenueHkd: 28800.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Performance Coaches',
    description: "Poliquin GBC body composition program with 6x6 supersets",
  },
  {
    programId: 'PRO035',
    name: "Eric Helms NLP",
    goal: 'Evidence-Based Physique',
    durationWeeks: 12,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'Performance',
    equipmentNeeded: "Full Gym",
    programStructure: "Periodized hypertrophy",
    progressionModel: "Double progression model",
    nutritionNotes: "Flexible dieting approach",
    safetyNotes: "Natural lifter timelines",
    timesUsed: 3,
    avgAdherencePct: 86.0,
    revenueHkd: 43200.0,
    clientSatisfaction: 4.8,
    status: 'Active',
    category: 'Performance Coaches',
    description: "Eric Helms Natural Bodybuilding Program with periodized hypertrophy",
  },
  {
    programId: 'PRO036',
    name: "Youth Athletic Development",
    goal: 'Foundation Ages 8-14',
    durationWeeks: 8,
    frequencyPerWeek: 3,
    difficulty: 'Beginner',
    method: 'Youth',
    equipmentNeeded: "Bodyweight, Light Medballs",
    programStructure: "Fundamental movement skills",
    progressionModel: "Add complexity",
    nutritionNotes: "Balanced diet, no restriction",
    safetyNotes: "Focus on fun, not load",
    timesUsed: 6,
    avgAdherencePct: 90.0,
    revenueHkd: 28800.0,
    clientSatisfaction: 4.7,
    status: 'Active',
    category: 'Youth & Senior',
    description: "Youth athletic development with fundamental movement skills",
  },
  {
    programId: 'PRO037',
    name: "Senior Mobility",
    goal: 'Functional Independence',
    durationWeeks: 6,
    frequencyPerWeek: 3,
    difficulty: 'Beginner',
    method: 'Senior',
    equipmentNeeded: "Bands, Light Weights, Chairs",
    programStructure: "Balance + strength + flexibility",
    progressionModel: "Decrease support",
    nutritionNotes: "Protein with each meal",
    safetyNotes: "Fall risk assessment",
    timesUsed: 8,
    avgAdherencePct: 88.0,
    revenueHkd: 19200.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Youth & Senior',
    description: "Senior mobility program for functional independence",
  },
  {
    programId: 'PRO038',
    name: "ACL Rehab",
    goal: 'Post-Surgery Recovery',
    durationWeeks: 24,
    frequencyPerWeek: 3,
    difficulty: 'Beginner',
    method: 'Rehab',
    equipmentNeeded: "PT Clinic, Then Gym",
    programStructure: "Phase-based: ROM to strength to agility",
    progressionModel: "Progress by phase criteria",
    nutritionNotes: "Anti-inflammatory, protein",
    safetyNotes: "Physio clearance each phase",
    timesUsed: 2,
    avgAdherencePct: 92.0,
    revenueHkd: 14400.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Rehab/Prehab',
    description: "ACL rehabilitation with phase-based progression",
  },
  {
    programId: 'PRO039',
    name: "Shoulder Prehab",
    goal: 'Rotator Cuff Health',
    durationWeeks: 6,
    frequencyPerWeek: 3,
    difficulty: 'Beginner',
    method: 'Rehab',
    equipmentNeeded: "Bands, Light Dumbbells",
    programStructure: "External rotation + YTWL + scapular work",
    progressionModel: "Increase band resistance",
    nutritionNotes: "Anti-inflammatory foods",
    safetyNotes: "Light load, high frequency",
    timesUsed: 5,
    avgAdherencePct: 87.0,
    revenueHkd: 24000.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Rehab/Prehab',
    description: "Rotator cuff and scapular prehab program for overhead athletes",
  },
  {
    programId: 'PRO040',
    name: "Yoga Flow",
    goal: 'Flexibility + Mindfulness',
    durationWeeks: 6,
    frequencyPerWeek: 3,
    difficulty: 'All Levels',
    method: 'Mind-Body',
    equipmentNeeded: "Mat, Blocks, Strap",
    programStructure: "Vinyasa or Hatha sequences",
    progressionModel: "Increase complexity",
    nutritionNotes: "Mindful eating",
    safetyNotes: "No ego in poses",
    timesUsed: 12,
    avgAdherencePct: 91.0,
    revenueHkd: 28800.0,
    clientSatisfaction: 4.7,
    status: 'Active',
    category: 'Mind-Body',
    description: "Yoga flow for flexibility and mindfulness",
  },
  {
    programId: 'PRO041',
    name: "Pilates Core",
    goal: 'Deep Core Stabilization',
    durationWeeks: 6,
    frequencyPerWeek: 3,
    difficulty: 'All Levels',
    method: 'Mind-Body',
    equipmentNeeded: "Mat, Reformer (Optional)",
    programStructure: "Mat Pilates or Reformer",
    progressionModel: "Add resistance or reps",
    nutritionNotes: "Balanced meals",
    safetyNotes: "Precision over speed",
    timesUsed: 9,
    avgAdherencePct: 89.0,
    revenueHkd: 21600.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Mind-Body',
    description: "Pilates core stabilization program",
  },
  {
    programId: 'PRO042',
    name: "Run-Lift Hybrid",
    goal: 'Running + Strength',
    durationWeeks: 8,
    frequencyPerWeek: 5,
    difficulty: 'Intermediate',
    method: 'Hybrid',
    equipmentNeeded: "Gym + Outdoor",
    programStructure: "3 runs + 2-3 lifts",
    progressionModel: "Increase run distance or lift load",
    nutritionNotes: "High carbs on run days",
    safetyNotes: "Separate hard days",
    timesUsed: 7,
    avgAdherencePct: 82.0,
    revenueHkd: 67200.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Hybrid',
    description: "Hybrid program balancing running and strength training",
  },
  {
    programId: 'PRO043',
    name: "Swim-Run Brick",
    goal: 'Aquatic + Land Endurance',
    durationWeeks: 8,
    frequencyPerWeek: 5,
    difficulty: 'Intermediate',
    method: 'Hybrid',
    equipmentNeeded: "Pool + Running Shoes",
    programStructure: "2 swims + 3 runs",
    progressionModel: "Increase swim distance",
    nutritionNotes: "Real food on long sessions",
    safetyNotes: "Shoulder prehab",
    timesUsed: 2,
    avgAdherencePct: 85.0,
    revenueHkd: 19200.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Hybrid',
    description: "Swim-run brick sessions for aquatic and land endurance",
  },
  {
    programId: 'PRO044',
    name: "F45 Training",
    goal: 'Team Functional Fitness',
    durationWeeks: 8,
    frequencyPerWeek: 5,
    difficulty: 'All Levels',
    method: 'Functional',
    equipmentNeeded: "F45 Studio Equipment",
    programStructure: "Circuit + resistance days",
    progressionModel: "Track rep improvements",
    nutritionNotes: "F45 meal plan option",
    safetyNotes: "Heart rate, reps",
    timesUsed: 15,
    avgAdherencePct: 77.0,
    revenueHkd: 72000.0,
    clientSatisfaction: 4.4,
    status: 'Active',
    category: 'Functional',
    description: "F45-style team functional fitness training",
  },
  {
    programId: 'PRO045',
    name: "OrangeTheory",
    goal: 'HR-Based Interval Training',
    durationWeeks: 8,
    frequencyPerWeek: 5,
    difficulty: 'All Levels',
    method: 'Functional',
    equipmentNeeded: "OT Studio Equipment",
    programStructure: "Zones 1-5 interval blocks",
    progressionModel: "Improve splat points",
    nutritionNotes: "OT nutrition guide",
    safetyNotes: "Monitor HR recovery",
    timesUsed: 10,
    avgAdherencePct: 78.0,
    revenueHkd: 48000.0,
    clientSatisfaction: 4.3,
    status: 'Active',
    category: 'Functional',
    description: "OrangeTheory-style heart rate based interval training",
  },
  {
    programId: 'PRO046',
    name: "Animal Flow",
    goal: 'Ground-Based Movement',
    durationWeeks: 6,
    frequencyPerWeek: 4,
    difficulty: 'All Levels',
    method: 'Functional',
    equipmentNeeded: "Mat, Open Floor",
    programStructure: "Animal locomotion patterns",
    progressionModel: "Flow complexity increase",
    nutritionNotes: "Anti-inflammatory focus",
    safetyNotes: "Wrist conditioning",
    timesUsed: 4,
    avgAdherencePct: 90.0,
    revenueHkd: 14400.0,
    clientSatisfaction: 4.7,
    status: 'Active',
    category: 'Functional',
    description: "Ground-based movement with animal locomotion patterns",
  },
  {
    programId: 'PRO047',
    name: "Tactical Fitness",
    goal: 'Military/LEO Readiness',
    durationWeeks: 12,
    frequencyPerWeek: 5,
    difficulty: 'Advanced',
    method: 'Functional',
    equipmentNeeded: "Ruck, Sandbag, Pull-Up Bar",
    programStructure: "Rucking + strength + runs",
    progressionModel: "Increase ruck weight",
    nutritionNotes: "High calories for load",
    safetyNotes: "Ruck with proper pack",
    timesUsed: 2,
    avgAdherencePct: 83.0,
    revenueHkd: 28800.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Functional',
    description: "Tactical fitness for military and law enforcement readiness",
  },
  {
    programId: 'PRO048',
    name: "Breathwork",
    goal: 'Recovery + Performance',
    durationWeeks: 4,
    frequencyPerWeek: 2,
    difficulty: 'All Levels',
    method: 'Mind-Body',
    equipmentNeeded: "",
    programStructure: "Box breathing, Wim Hof, diaphragmatic",
    progressionModel: "Increase hold times",
    nutritionNotes: "",
    safetyNotes: "Don't hyperventilate",
    timesUsed: 3,
    avgAdherencePct: 93.0,
    revenueHkd: 9600.0,
    clientSatisfaction: 4.8,
    status: 'Active',
    category: 'Mind-Body',
    description: "Breathwork training for recovery and performance",
  },
  {
    programId: 'PRO049',
    name: "Boxing Conditioning",
    goal: 'Ring Fitness + Power',
    durationWeeks: 8,
    frequencyPerWeek: 5,
    difficulty: 'Intermediate',
    method: 'Sport-Specific',
    equipmentNeeded: "Heavy Bag, Speed Bag, Jump Rope",
    programStructure: "Bag work + road work + core",
    progressionModel: "Increase bag rounds",
    nutritionNotes: "Cut weight gradually",
    safetyNotes: "Hand wraps mandatory",
    timesUsed: 5,
    avgAdherencePct: 82.0,
    revenueHkd: 48000.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Sports-Specific',
    description: "Boxing conditioning for ring fitness and power",
  },
  {
    programId: 'PRO050',
    name: "Muay Thai",
    goal: 'Thai Boxing Endurance',
    durationWeeks: 8,
    frequencyPerWeek: 5,
    difficulty: 'Intermediate',
    method: 'Sport-Specific',
    equipmentNeeded: "Heavy Bag, Thai Pads, Shinguards",
    programStructure: "Kicks, knees, clinch work, conditioning",
    progressionModel: "Add kicks per round",
    nutritionNotes: "Weight management",
    safetyNotes: "Shin conditioning gradual",
    timesUsed: 3,
    avgAdherencePct: 80.0,
    revenueHkd: 28800.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Sports-Specific',
    description: "Muay Thai training for endurance and technique",
  },
  {
    programId: 'PRO051',
    name: "DUP Wave Loading",
    goal: 'Strength + Hypertrophy',
    durationWeeks: 8,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'DUP',
    equipmentNeeded: "Full Gym",
    programStructure: "Hypertrophy/strength/power rotation",
    progressionModel: "Wave loading weekly",
    nutritionNotes: "Carbs peri-workout",
    safetyNotes: "Auto-regulate by feel",
    timesUsed: 4,
    avgAdherencePct: 81.0,
    revenueHkd: 38400.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Strength Training',
    description: "Daily Undulating Periodization with wave loading",
  },
  {
    programId: 'PRO052',
    name: "Full-Body Frequency",
    goal: 'Strength Foundation',
    durationWeeks: 8,
    frequencyPerWeek: 3,
    difficulty: 'Beginner',
    method: 'Full-Body',
    equipmentNeeded: "Full Gym",
    programStructure: "3x/week full-body compounds",
    progressionModel: "Double progression",
    nutritionNotes: "Moderate surplus",
    safetyNotes: "Form over load always",
    timesUsed: 11,
    avgAdherencePct: 77.0,
    revenueHkd: 52800.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Strength Training',
    description: "Full-body frequency program for strength foundation",
  },
  {
    programId: 'PRO053',
    name: "Conjugate Method",
    goal: 'Power Development',
    durationWeeks: 12,
    frequencyPerWeek: 4,
    difficulty: 'Advanced',
    method: 'Conjugate',
    equipmentNeeded: "Powerlifting Gym",
    programStructure: "Max effort + dynamic effort days",
    progressionModel: "Rotate ME exercises",
    nutritionNotes: "Surplus + creatine",
    safetyNotes: "Monitor fatigue closely",
    timesUsed: 3,
    avgAdherencePct: 79.0,
    revenueHkd: 36000.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Strength Training',
    description: "Conjugate method for power development and strength",
  },
  {
    programId: 'PRO054',
    name: "Block Periodization",
    goal: 'Peaking Program',
    durationWeeks: 12,
    frequencyPerWeek: 4,
    difficulty: 'Advanced',
    method: 'Block',
    equipmentNeeded: "Full Gym",
    programStructure: "Accumulation/trans realization blocks",
    progressionModel: "Block-to-block progression",
    nutritionNotes: "Phase-matched nutrition",
    safetyNotes: "Deload between blocks",
    timesUsed: 4,
    avgAdherencePct: 80.0,
    revenueHkd: 48000.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Strength Training',
    description: "Block periodization for competition peaking",
  },
  {
    programId: 'PRO055',
    name: "Linear Periodization",
    goal: 'Beginner Strength',
    durationWeeks: 12,
    frequencyPerWeek: 3,
    difficulty: 'Beginner',
    method: 'Linear',
    equipmentNeeded: "Basic Gym",
    programStructure: "3x/week progressive load",
    progressionModel: "Add weight each session",
    nutritionNotes: "Moderate surplus",
    safetyNotes: "Rest when needed",
    timesUsed: 14,
    avgAdherencePct: 75.0,
    revenueHkd: 67200.0,
    clientSatisfaction: 4.4,
    status: 'Active',
    category: 'Strength Training',
    description: "Classic linear periodization for beginner strength",
  },
  {
    programId: 'PRO056',
    name: "Daily 5x5",
    goal: 'Strength for Busy',
    durationWeeks: 8,
    frequencyPerWeek: 3,
    difficulty: 'Beginner',
    method: '5x5',
    equipmentNeeded: "Basic Gym",
    programStructure: "5 compound lifts per session",
    progressionModel: "Add weight when 5x5 achieved",
    nutritionNotes: "Moderate surplus",
    safetyNotes: "Time efficient",
    timesUsed: 9,
    avgAdherencePct: 76.0,
    revenueHkd: 43200.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Strength Training',
    description: "Daily 5x5 program for busy schedules",
  },
  {
    programId: 'PRO057',
    name: "Powerbuilding",
    goal: 'Strength + Size',
    durationWeeks: 12,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'Powerbuilding',
    equipmentNeeded: "Full Gym",
    programStructure: "Mix of powerlifting + bodybuilding",
    progressionModel: "Periodized blocks",
    nutritionNotes: "High protein, surplus",
    safetyNotes: "Balance heavy and volume",
    timesUsed: 6,
    avgAdherencePct: 83.0,
    revenueHkd: 57600.0,
    clientSatisfaction: 4.7,
    status: 'Active',
    category: 'Strength Training',
    description: "Powerbuilding combining powerlifting and bodybuilding",
  },
  {
    programId: 'PRO058',
    name: "Oly Lifting Fundamentals",
    goal: 'Weightlifting Base',
    durationWeeks: 12,
    frequencyPerWeek: 5,
    difficulty: 'Intermediate',
    method: 'Olympic',
    equipmentNeeded: "Weightlifting Platform",
    programStructure: "Snatch + Clean & Jerk practice",
    progressionModel: "Technical progression",
    nutritionNotes: "Moderate surplus",
    safetyNotes: "Get coaching",
    timesUsed: 2,
    avgAdherencePct: 85.0,
    revenueHkd: 24000.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Strength Training',
    description: "Olympic weightlifting fundamentals with technical focus",
  },
  {
    programId: 'PRO059',
    name: "Calisthenics Pro",
    goal: 'Bodyweight Mastery',
    durationWeeks: 12,
    frequencyPerWeek: 4,
    difficulty: 'Advanced',
    method: 'Calisthenics',
    equipmentNeeded: "Pull-Up Bar, Parallettes",
    programStructure: "Progressive bodyweight skills",
    progressionModel: "Skill-based progression",
    nutritionNotes: "Moderate surplus",
    safetyNotes: "Joint prep essential",
    timesUsed: 7,
    avgAdherencePct: 88.0,
    revenueHkd: 33600.0,
    clientSatisfaction: 4.7,
    status: 'Active',
    category: 'Strength Training',
    description: "Advanced calisthenics with progressive skill work",
  },
  {
    programId: 'PRO060',
    name: "Strongman Training",
    goal: 'Functional Strength',
    durationWeeks: 12,
    frequencyPerWeek: 4,
    difficulty: 'Advanced',
    method: 'Strongman',
    equipmentNeeded: "Strongman Equipment",
    programStructure: "Events-based training",
    progressionModel: "Increase event weights",
    nutritionNotes: "High calories",
    safetyNotes: "Technique for each event",
    timesUsed: 2,
    avgAdherencePct: 82.0,
    revenueHkd: 19200.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Specific Programs',
    description: "Strongman event training for functional strength",
  },
  {
    programId: 'PRO061',
    name: "Parkour Conditioning",
    goal: 'Movement Training',
    durationWeeks: 8,
    frequencyPerWeek: 4,
    difficulty: 'Intermediate',
    method: 'Parkour',
    equipmentNeeded: "Parkour Gym/Outdoor",
    programStructure: "Jumping, climbing, rolling",
    progressionModel: "Progressive difficulty",
    nutritionNotes: "Moderate nutrition",
    safetyNotes: "Land softly always",
    timesUsed: 3,
    avgAdherencePct: 86.0,
    revenueHkd: 28800.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Specific Programs',
    description: "Parkour conditioning for movement and agility",
  },
  {
    programId: 'PRO062',
    name: "Gymnastics Strength",
    goal: 'Bodyweight Strength',
    durationWeeks: 12,
    frequencyPerWeek: 4,
    difficulty: 'Advanced',
    method: 'Gymnastics',
    equipmentNeeded: "Gymnastics Rings, Parallettes",
    programStructure: "GST progressions",
    progressionModel: "Hold-to-rep progression",
    nutritionNotes: "Moderate surplus",
    safetyNotes: "Wrist conditioning daily",
    timesUsed: 2,
    avgAdherencePct: 90.0,
    revenueHkd: 19200.0,
    clientSatisfaction: 4.8,
    status: 'Active',
    category: 'Specific Programs',
    description: "Gymnastics strength training with GST progressions",
  },
  {
    programId: 'PRO063',
    name: "Climbing Training",
    goal: 'Rock Climbing Prep',
    durationWeeks: 8,
    frequencyPerWeek: 3,
    difficulty: 'Intermediate',
    method: 'Climbing',
    equipmentNeeded: "Climbing Wall, Hangboard",
    programStructure: "Finger strength + technique",
    progressionModel: "Hangboard progression",
    nutritionNotes: "Moderate deficit",
    safetyNotes: "Finger health priority",
    timesUsed: 3,
    avgAdherencePct: 87.0,
    revenueHkd: 28800.0,
    clientSatisfaction: 4.7,
    status: 'Active',
    category: 'Specific Programs',
    description: "Rock climbing training with finger strength focus",
  },
  {
    programId: 'PRO064',
    name: "Surf Fitness",
    goal: 'Wave Readiness',
    durationWeeks: 8,
    frequencyPerWeek: 3,
    difficulty: 'Intermediate',
    method: 'Sport-Specific',
    equipmentNeeded: "Surfboard, Balance Board",
    programStructure: "Paddling, pop-ups, balance",
    progressionModel: "Increase paddle endurance",
    nutritionNotes: "Balanced diet",
    safetyNotes: "Shoulder health",
    timesUsed: 2,
    avgAdherencePct: 84.0,
    revenueHkd: 19200.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Sports-Specific',
    description: "Surf fitness for paddling endurance and balance",
  },
  {
    programId: 'PRO065',
    name: "Ski Conditioning",
    goal: 'Slope Readiness',
    durationWeeks: 8,
    frequencyPerWeek: 3,
    difficulty: 'Intermediate',
    method: 'Sport-Specific',
    equipmentNeeded: "Leg Press, Balance Tools",
    programStructure: "Leg strength + proprioception",
    progressionModel: "Increase eccentric load",
    nutritionNotes: "Moderate carbs",
    safetyNotes: "Knee stability",
    timesUsed: 3,
    avgAdherencePct: 83.0,
    revenueHkd: 28800.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Sports-Specific',
    description: "Ski conditioning with leg strength and proprioception",
  },
  {
    programId: 'PRO066',
    name: "Pre-Wedding Shred",
    goal: 'Aesthetic Quick Fix',
    durationWeeks: 8,
    frequencyPerWeek: 5,
    difficulty: 'All Levels',
    method: 'Seasonal',
    equipmentNeeded: "Full Gym or Home",
    programStructure: "High frequency, calorie deficit",
    progressionModel: "Progressive cardio increase",
    nutritionNotes: "Aggressive deficit",
    safetyNotes: "Maintain muscle mass",
    timesUsed: 28,
    avgAdherencePct: 71.0,
    revenueHkd: 134400.0,
    clientSatisfaction: 4.3,
    status: 'Active',
    category: 'Seasonal',
    description: "Pre-wedding body transformation program",
  },
  {
    programId: 'PRO067',
    name: "Postpartum Recovery",
    goal: 'Safe Return to Fitness',
    durationWeeks: 12,
    frequencyPerWeek: 3,
    difficulty: 'Beginner',
    method: 'Rehab',
    equipmentNeeded: "Mat, Light Weights",
    programStructure: "Core rehab, diastasis-safe",
    progressionModel: "Progress by phase",
    nutritionNotes: "Adequate calories",
    safetyNotes: "Pelvic floor first",
    timesUsed: 8,
    avgAdherencePct: 92.0,
    revenueHkd: 24000.0,
    clientSatisfaction: 4.7,
    status: 'Active',
    category: 'Rehab/Prehab',
    description: "Postpartum recovery with core rehabilitation focus",
  },
  {
    programId: 'PRO068',
    name: "Corporate Wellness",
    goal: 'Office Worker Health',
    durationWeeks: 8,
    frequencyPerWeek: 2,
    difficulty: 'Beginner',
    method: 'Wellness',
    equipmentNeeded: "Basic Gym",
    programStructure: "Desk-break mobility + strength",
    progressionModel: "Add sessions weekly",
    nutritionNotes: "Balanced nutrition",
    safetyNotes: "Posture improvement",
    timesUsed: 6,
    avgAdherencePct: 85.0,
    revenueHkd: 19200.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Rehab/Prehab',
    description: "Corporate wellness for office worker health",
  },
  {
    programId: 'PRO069',
    name: "Post-Rehab Strength",
    goal: 'Return to Lifting',
    durationWeeks: 12,
    frequencyPerWeek: 3,
    difficulty: 'Intermediate',
    method: 'Rehab',
    equipmentNeeded: "Full Gym",
    programStructure: "Gradual return to compounds",
    progressionModel: "Pain-free progression",
    nutritionNotes: "Protein for recovery",
    safetyNotes: "Physio-guided",
    timesUsed: 4,
    avgAdherencePct: 89.0,
    revenueHkd: 28800.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Rehab/Prehab',
    description: "Post-rehabilitation strength return program",
  },
  {
    programId: 'PRO070',
    name: "Meditation + Movement",
    goal: 'Mind-Body Balance',
    durationWeeks: 6,
    frequencyPerWeek: 3,
    difficulty: 'All Levels',
    method: 'Mind-Body',
    equipmentNeeded: "Mat, Quiet Space",
    programStructure: "Movement + mindfulness practice",
    progressionModel: "Increase duration",
    nutritionNotes: "Anti-inflammatory",
    safetyNotes: "Consistency over intensity",
    timesUsed: 5,
    avgAdherencePct: 91.0,
    revenueHkd: 14400.0,
    clientSatisfaction: 4.7,
    status: 'Active',
    category: 'Mind-Body',
    description: "Meditation combined with mindful movement",
  },
  {
    programId: 'PRO071',
    name: "OCR Race Prep",
    goal: 'Obstacle Course Ready',
    durationWeeks: 10,
    frequencyPerWeek: 5,
    difficulty: 'Intermediate',
    method: 'OCR',
    equipmentNeeded: "Ropes, Walls, Monkey Bars",
    programStructure: "Climbing + running + grip",
    progressionModel: "Increase obstacle reps",
    nutritionNotes: "Carb loading pre-race",
    safetyNotes: "Grip strength critical",
    timesUsed: 3,
    avgAdherencePct: 84.0,
    revenueHkd: 33600.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Functional',
    description: "Obstacle Course Race preparation program",
  },
  {
    programId: 'PRO072',
    name: "Spartan Training",
    goal: 'Spartan Race Ready',
    durationWeeks: 10,
    frequencyPerWeek: 5,
    difficulty: 'Advanced',
    method: 'OCR',
    equipmentNeeded: "Full OCR Setup",
    programStructure: "Burpees, climbs, carries, runs",
    progressionModel: "Simulate race conditions",
    nutritionNotes: "Race nutrition practice",
    safetyNotes: "Burpee tolerance",
    timesUsed: 4,
    avgAdherencePct: 82.0,
    revenueHkd: 38400.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Functional',
    description: "Spartan Race specific training with race simulation",
  },
  {
    programId: 'PRO073',
    name: "Hypertrophy Specialization",
    goal: 'Laggin Body Part',
    durationWeeks: 6,
    frequencyPerWeek: 5,
    difficulty: 'Intermediate',
    method: 'Hypertrophy',
    equipmentNeeded: "Full Gym",
    programStructure: "High volume for weak body part",
    progressionModel: "Add sets weekly",
    nutritionNotes: "Moderate surplus",
    safetyNotes: "Recovery prioritized",
    timesUsed: 10,
    avgAdherencePct: 80.0,
    revenueHkd: 48000.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Strength Training',
    description: "Specialized hypertrophy for lagging body parts",
  },
  {
    programId: 'PRO074',
    name: "Fat Loss Plateau Breaker",
    goal: 'Break Through Stall',
    durationWeeks: 4,
    frequencyPerWeek: 5,
    difficulty: 'Intermediate',
    method: 'MetCon',
    equipmentNeeded: "Full Gym",
    programStructure: "Shock tactics, new stimuli",
    progressionModel: "Change variables weekly",
    nutritionNotes: "Calorie cycling",
    safetyNotes: "Monitor fatigue",
    timesUsed: 14,
    avgAdherencePct: 74.0,
    revenueHkd: 33600.0,
    clientSatisfaction: 4.3,
    status: 'Active',
    category: 'Weight Loss',
    description: "Plateau breaker program for stalled fat loss",
  },
  {
    programId: 'PRO075',
    name: "Muscle Gain for Ectomorphs",
    goal: 'Hardgainer Program',
    durationWeeks: 12,
    frequencyPerWeek: 4,
    difficulty: 'Beginner',
    method: 'Hypertrophy',
    equipmentNeeded: "Full Gym",
    programStructure: "Lower volume, higher frequency",
    progressionModel: "Add weight when possible",
    nutritionNotes: "Aggressive surplus",
    safetyNotes: "Rest adequately",
    timesUsed: 8,
    avgAdherencePct: 76.0,
    revenueHkd: 38400.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Strength Training',
    description: "Muscle gain program tailored for ectomorph hardgainers",
  },
  {
    programId: 'PRO076',
    name: "Fat Loss for Endomorphs",
    goal: 'Efficient Fat Loss',
    durationWeeks: 12,
    frequencyPerWeek: 4,
    difficulty: 'Beginner',
    method: 'Fat Loss',
    equipmentNeeded: "Full Gym",
    programStructure: "Higher volume, metabolic work",
    progressionModel: "Progressive cardio",
    nutritionNotes: "Moderate deficit",
    safetyNotes: "Carb timing important",
    timesUsed: 12,
    avgAdherencePct: 73.0,
    revenueHkd: 57600.0,
    clientSatisfaction: 4.4,
    status: 'Active',
    category: 'Weight Loss',
    description: "Fat loss program optimized for endomorph body type",
  },
  {
    programId: 'PRO077',
    name: "Mesomorph Maintenance",
    goal: 'Athletic Physique',
    durationWeeks: 8,
    frequencyPerWeek: 3,
    difficulty: 'Intermediate',
    method: 'Maintenance',
    equipmentNeeded: "Full Gym",
    programStructure: "Balanced strength + cardio",
    progressionModel: "Maintain performance",
    nutritionNotes: "Maintenance calories",
    safetyNotes: "Consistent training",
    timesUsed: 7,
    avgAdherencePct: 84.0,
    revenueHkd: 33600.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Strength Training',
    description: "Maintenance program for mesomorph athletic physique",
  },
  {
    programId: 'PRO078',
    name: "Wedding Dress Ready",
    goal: 'Bridal Fitness',
    durationWeeks: 6,
    frequencyPerWeek: 4,
    difficulty: 'All Levels',
    method: 'Seasonal',
    equipmentNeeded: "Gym or Home",
    programStructure: "Tone + shape, not bulk",
    progressionModel: "Progressive difficulty",
    nutritionNotes: "Moderate deficit",
    safetyNotes: "Arm + back focus",
    timesUsed: 16,
    avgAdherencePct: 72.0,
    revenueHkd: 57600.0,
    clientSatisfaction: 4.3,
    status: 'Active',
    category: 'Seasonal',
    description: "Bridal fitness program for wedding dress readiness",
  },
  {
    programId: 'PRO079',
    name: "Holiday Survival",
    goal: 'Stay Fit Through Holidays',
    durationWeeks: 6,
    frequencyPerWeek: 3,
    difficulty: 'All Levels',
    method: 'Seasonal',
    equipmentNeeded: "Minimal Equipment",
    programStructure: "Quick effective sessions",
    progressionModel: "Maintain consistency",
    nutritionNotes: "Flexible nutrition",
    safetyNotes: "Short sessions",
    timesUsed: 9,
    avgAdherencePct: 78.0,
    revenueHkd: 28800.0,
    clientSatisfaction: 4.4,
    status: 'Active',
    category: 'Seasonal',
    description: "Holiday fitness survival with minimal equipment",
  },
  {
    programId: 'PRO080',
    name: "Post-Holiday Reset",
    goal: 'Back on Track',
    durationWeeks: 4,
    frequencyPerWeek: 4,
    difficulty: 'All Levels',
    method: 'Seasonal',
    equipmentNeeded: "Full Gym",
    programStructure: "Rebuild routine gradually",
    progressionModel: "Add intensity weekly",
    nutritionNotes: "Return to baseline",
    safetyNotes: "No crash dieting",
    timesUsed: 18,
    avgAdherencePct: 70.0,
    revenueHkd: 28800.0,
    clientSatisfaction: 4.2,
    status: 'Active',
    category: 'Seasonal',
    description: "Post-holiday routine reset program",
  },
  {
    programId: 'PRO081',
    name: "Ramadan Training",
    goal: 'Fasting-Safe Fitness',
    durationWeeks: 4,
    frequencyPerWeek: 3,
    difficulty: 'All Levels',
    method: 'Seasonal',
    equipmentNeeded: "Basic Gym",
    programStructure: "Low volume, maintenance focus",
    progressionModel: "Maintain strength",
    nutritionNotes: "Hydration priority",
    safetyNotes: "Train before breaking fast",
    timesUsed: 5,
    avgAdherencePct: 82.0,
    revenueHkd: 12000.0,
    clientSatisfaction: 4.5,
    status: 'Active',
    category: 'Seasonal',
    description: "Training program adapted for Ramadan fasting",
  },
  {
    programId: 'PRO082',
    name: "Vacation Shred",
    goal: 'Quick Prep',
    durationWeeks: 4,
    frequencyPerWeek: 5,
    difficulty: 'Intermediate',
    method: 'Seasonal',
    equipmentNeeded: "Full Gym",
    programStructure: "Intensified training block",
    progressionModel: "Add sessions",
    nutritionNotes: "Moderate deficit",
    safetyNotes: "Water manipulation",
    timesUsed: 11,
    avgAdherencePct: 75.0,
    revenueHkd: 26400.0,
    clientSatisfaction: 4.3,
    status: 'Active',
    category: 'Seasonal',
    description: "Quick vacation preparation shred program",
  },
  {
    programId: 'PRO083',
    name: "Photo Shoot Ready",
    goal: 'Peak Condition',
    durationWeeks: 2,
    frequencyPerWeek: 6,
    difficulty: 'Advanced',
    method: 'Seasonal',
    equipmentNeeded: "Full Gym",
    programStructure: "Peak week protocol",
    progressionModel: "Coach-managed",
    nutritionNotes: "Peak week protocol",
    safetyNotes: "Professional guidance",
    timesUsed: 6,
    avgAdherencePct: 77.0,
    revenueHkd: 14400.0,
    clientSatisfaction: 4.4,
    status: 'Active',
    category: 'Seasonal',
    description: "Photo shoot peak condition protocol",
  },
  {
    programId: 'PRO084',
    name: "Transformation Challenge",
    goal: '12-Week Complete',
    durationWeeks: 12,
    frequencyPerWeek: 5,
    difficulty: 'All Levels',
    method: 'Transformation',
    equipmentNeeded: "Full Gym",
    programStructure: "Progressive overload + cardio",
    progressionModel: "Weekly progression",
    nutritionNotes: "Phase-matched nutrition",
    safetyNotes: "Before/after photos",
    timesUsed: 20,
    avgAdherencePct: 80.0,
    revenueHkd: 96000.0,
    clientSatisfaction: 4.6,
    status: 'Active',
    category: 'Seasonal',
    description: "Complete 12-week body transformation challenge",
  },
];

/** Get unique categories */
export const PROGRAM_CATEGORIES = [...new Set(PROGRAMS_LIBRARY.map(p => p.category))].sort();

/** Get unique goals */
export const PROGRAM_GOALS = [...new Set(PROGRAMS_LIBRARY.map(p => p.goal))].sort();

/** Get unique methods */
export const PROGRAM_METHODS = [...new Set(PROGRAMS_LIBRARY.map(p => p.method))].sort();

/** Filter programs by goal */
export function getProgramsByGoal(goal: string): ProgramLibraryData[] {
  return PROGRAMS_LIBRARY.filter(p => p.goal === goal);
}

/** Filter programs by category */
export function getProgramsByCategory(category: string): ProgramLibraryData[] {
  return PROGRAMS_LIBRARY.filter(p => p.category === category);
}

/** Filter programs by difficulty */
export function getProgramsByDifficulty(difficulty: string): ProgramLibraryData[] {
  return PROGRAMS_LIBRARY.filter(p => p.difficulty === difficulty);
}

/** Search programs */
export function searchPrograms(query: string): ProgramLibraryData[] {
  const q = query.toLowerCase();
  return PROGRAMS_LIBRARY.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.goal.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q) ||
    p.method.toLowerCase().includes(q)
  );
}

/** Get program by ID */
export function getProgramById(id: string): ProgramLibraryData | undefined {
  return PROGRAMS_LIBRARY.find(p => p.programId === id);
}
