import type { LeaderboardEntry } from './types'

export const MOCK_WORKOUT_NAME = 'Upper Body A — Day 2'
export const MOCK_PROGRAM_ID = '101'

export const mockLeaderboardEntries: LeaderboardEntry[] = [
  {
    id: 'lb-1',
    rank: 1,
    clientId: 'c-sarah',
    clientName: 'Sarah Chen',
    clientInitials: 'SC',
    gender: 'female',
    resultValue: 62.5,
    resultType: 'load',
    resultLabel: '62.5 kg × 10 reps',
    isRx: true,
    date: '2026-06-08',
    likes: 24,
    likedByMe: false,
    prBadges: ['Bench Press PR'],
  },
  {
    id: 'lb-2',
    rank: 2,
    clientId: 'c-marcus',
    clientName: 'Marcus Johnson',
    clientInitials: 'MJ',
    gender: 'male',
    resultValue: 60,
    resultType: 'load',
    resultLabel: '60 kg × 10 reps',
    isRx: true,
    date: '2026-06-07',
    likes: 18,
    likedByMe: true,
    prBadges: [],
  },
  {
    id: 'lb-3',
    rank: 3,
    clientId: 'c-alex',
    clientName: 'Alex Rivera',
    clientInitials: 'AR',
    gender: 'male',
    resultValue: 55,
    resultType: 'load',
    resultLabel: '55 kg × 10 reps',
    isRx: false,
    date: '2026-06-08',
    likes: 12,
    likedByMe: false,
    prBadges: [],
  },
  {
    id: 'lb-4',
    rank: 4,
    clientId: 'c-emma',
    clientName: 'Emma Wilson',
    clientInitials: 'EW',
    gender: 'female',
    resultValue: 50,
    resultType: 'load',
    resultLabel: '50 kg × 10 reps',
    isRx: false,
    date: '2026-06-05',
    likes: 9,
    likedByMe: false,
    prBadges: [],
  },
  {
    id: 'lb-5',
    rank: 5,
    clientId: 'c-david',
    clientName: 'David Kim',
    clientInitials: 'DK',
    gender: 'male',
    resultValue: 70,
    resultType: 'load',
    resultLabel: '70 kg × 8 reps',
    isRx: true,
    date: '2026-06-09',
    likes: 31,
    likedByMe: false,
    prBadges: ['Bench Press PR', 'Volume PR'],
  },
  {
    id: 'lb-6',
    rank: 6,
    clientId: 'c-olivia',
    clientName: 'Olivia Martinez',
    clientInitials: 'OM',
    gender: 'female',
    resultValue: 45,
    resultType: 'load',
    resultLabel: '45 kg × 12 reps',
    isRx: false,
    date: '2026-06-06',
    likes: 7,
    likedByMe: false,
    prBadges: [],
  },
  {
    id: 'lb-7',
    rank: 7,
    clientId: 'c-james',
    clientName: 'James Thompson',
    clientInitials: 'JT',
    gender: 'male',
    resultValue: 65,
    resultType: 'load',
    resultLabel: '65 kg × 9 reps',
    isRx: true,
    date: '2026-06-04',
    likes: 15,
    likedByMe: false,
    prBadges: [],
  },
  {
    id: 'lb-8',
    rank: 8,
    clientId: 'c-current',
    clientName: 'You',
    clientInitials: 'YU',
    gender: 'other',
    resultValue: 57.5,
    resultType: 'load',
    resultLabel: '57.5 kg × 10 reps',
    isRx: true,
    date: '2026-06-09',
    likes: 3,
    likedByMe: false,
    prBadges: [],
  },
]
